### ISSUE TITLE
验证码一直发送失败

### ISSUE THREAD

**Issue by h88782481** [oddfar/campus-imaotai#10]
如题
![image](https://github.com/oddfar/campus-imaotai/assets/54714341/e8a1f46e-5827-4783-93ab-a01227b51579)

**Comment by oddfar** [comment]
检查你的网络状态

**Comment by oddfar** [comment]
是用的非大陆的吗？

**Comment by h88782481** [comment]
> 是用的非大陆的吗？

对，加宽

**Comment by funnyData** [comment]
用的香港的云服务器同样不能发验证码

**Comment by oddfar** [comment]
非大陆的好像不行

**Comment by h88782481** [comment]
> 非大陆的好像不行

我的是大陆内的，家庭宽带，不知道为啥不行

**Comment by oddfar** [comment]
> 

同一网络，app可以预约？

**Comment by h88782481** [comment]
> > 
> 
> 同一网络，app可以预约？

可以，我怀疑是我用的服务器的原因，我用的arm32位处理器的服务器
