### ISSUE TITLE
docker-compose build 报错

### ISSUE THREAD

**Issue by qhq** [oddfar/campus-imaotai#105]
Step 1/7 : FROM java:8
manifest for java:8 not found: manifest unknown: manifest unknown
ERROR: Service 'campus-server' failed to build : Build failed

**Comment by Dlian-Zero** [comment]
Step 1/7 : FROM java:8
manifest for java:8 not found: manifest unknown: manifest unknown
ERROR: Service 'campus-server' failed to build
