### ISSUE TITLE
设备id如何获取呀，求告知

### ISSUE THREAD

**Issue by gl-guoliang** [oddfar/campus-imaotai#107]
因为无法通过在线获取验证码新增用户，  我使用的是直接新增，手动填写token等信息，设备id不知如何获取
<img width="733" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/81785354/13b9112a-6a6d-43fb-8e1a-a92fe19ee79d">

**Comment by qhq** [comment]
验证码问题试试手机号后面加个空格，提示错误，再把空格删掉再试。我这样试几次就可以发送了。

**Comment by oddfar** [comment]
请求头里的，device_id 就是设备id
