### ISSUE TITLE
缺少MT-V请求头

### ISSUE THREAD

**Issue by hitoxiao** [oddfar/campus-imaotai#109]
茅台申购接口请求头好像少了MT-V这个请求头，会不会导致官方识别到非人为申购？
自己逆向的接口在青龙申购了好久，一直没成功过，不知道是不是被识别了还是咋的。
![image](https://github.com/oddfar/campus-imaotai/assets/115056774/482b1af9-b5af-4466-ab3a-8328bc2751d9)
![image](https://github.com/oddfar/campus-imaotai/assets/115056774/4501dac1-74e1-45f7-a6d0-cae5d5c4d1ab)

**Comment by tinoyoung** [comment]
跪求MT-V算法

**Comment by tinoyoung** [comment]
> 茅台申购接口请求头好像少了MT-V这个请求头，会不会导致官方识别到非人为申购？ 自己逆向的接口在青龙申购了好久，一直没成功过，不知道是不是被识别了还是咋的。 ![image](https://private-user-images.githubusercontent.com/115056774/270521542-482b1af9-b5af-4466-ab3a-8328bc2751d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTcxNTEsIm5iZiI6MTcwNDAxNjg1MSwicGF0aCI6Ii8xMTUwNTY3NzQvMjcwNTIxNTQyLTQ4MmIxYWY5LWI1YWYtNDQ2Ni1hYjNhLTgzMjhiYzI3NTFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxMDAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmNlNjM5YzkzYjZjOWQ2ODZhZjNlZWU5YmM1MmYxZDU2MDA3YmI3NDFlOWQ3M2M2M2UyYmU2ODQxYjdkOTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l6er8Cz9eQ5pmvswM5FciDmB-rhPQex33epxBVlJAXg) ![image](https://private-user-images.githubusercontent.com/115056774/270521895-4501dac1-74e1-45f7-a6d0-cae5d5c4d1ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTcxNTEsIm5iZiI6MTcwNDAxNjg1MSwicGF0aCI6Ii8xMTUwNTY3NzQvMjcwNTIxODk1LTQ1MDFkYWMxLTc0ZTEtNDVmNy1hNmQwLWNhZTVkNWM0ZDFhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQxMDAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2E4MGJmZmRkZjIzNjVkYjgxMmUzYzIxOGE1YjcxZWJhZGQwNzIzNmUxOTIwODc0NDc4YzlkZWU4ZDUzOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vKSfikFTHZTAaSuDxJ72aRqS_SU7PbROZkgrPEbn_fs)

跪求MT-V算法
