### ISSUE TITLE
请问添加账号时填写的 门店商品ID 具体意义是？

### ISSUE THREAD

**Issue by uclort** [oddfar/campus-imaotai#117]
一开始理解的是预约的店铺，但是发现今早上预约成功的门店不是这家店铺

是因为指定的店铺没有名额了？然后自动选择的指定店铺最近的店铺吗？

文档里没有找到相关说明。

**Comment by uclort** [comment]
另外还有类型里的预约我的位置附近，请问这个我的位置要去哪里设置呢？

**Comment by oddfar** [comment]
> 另外还有类型里的预约我的位置附近，请问这个我的位置要去哪里设置呢？

位置就是所填的门店位置

**Comment by oddfar** [comment]
填写门店信息作用是，需要省份、城市、经纬度。之前版本是直接填写信息，但反馈很多用户填不对，就改成强制填写门店信息，防止配置错误
预约类型有2种：本市出货量最大、本省位置最近（有时候会选到其他市）

**Comment by uclort** [comment]
> 填写门店信息作用是，需要省份、城市、经纬度。之前版本是直接填写信息，但反馈很多用户填不对，就改成强制填写门店信息，防止配置错误
> 
> 预约类型有2种：本市出货量最大、本省位置最近（有时候会选到其他市）

谢谢，了解了。
