### ISSUE TITLE
成功创建后redis容器一直起不来看报错提示TCP*****

### ISSUE THREAD

**Issue by vcgg** [oddfar/campus-imaotai#12]
[root@VM-12-10-centos campus-imt-V1.0.1]# docker logs -f campus-redis 
1:C 11 Jul 2023 07:54:16.728 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Jul 2023 07:54:16.728 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Jul 2023 07:54:16.728 # Configuration loaded
1:M 11 Jul 2023 07:54:16.728 * monotonic clock: POSIX clock_gettime
1:M 11 Jul 2023 07:54:16.729 * Running mode=standalone, port=6379.
1:M 11 Jul 2023 07:54:16.729 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 11 Jul 2023 07:54:16.729 # Server initialized
1:M 11 Jul 2023 07:54:16.729 # Fatal: Can't initialize Background Jobs

我已经把对应的值改为1024，并且也sysctl -p生效了，也尝试重启过服务器，还是提示这个报错

**Comment by oddfar** [comment]
我不寄丢了，坐等客户端版吧
有基础就直接搭建吧，不用docker

**Comment by vcgg** [comment]
> 我不寄丢了，坐等客户端版吧 有基础就直接搭建吧，不用docker

收到，感谢回复
