### ISSUE TITLE
新增用户-验证码获取失败

### ISSUE THREAD

**Issue by gl-guoliang** [oddfar/campus-imaotai#122]
尝试登录了几十次，只成功一次，截图为最新缺陷信息

日志详细内容在下面连接中
https://github.com/oddfar/campus-imaotai/issues/103#issue-1909965666

<img width="1418" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/81785354/b778b849-1ae5-4040-ade5-7cb7bc3c113f">
<img width="1438" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/81785354/a515f4f0-12b4-448d-a9e8-d5f6a15c94fc">
<img width="1426" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/81785354/7941bee4-87a4-4d10-8270-9e9d4162902e">

**Comment by oddfar** [comment]
短信接口短时间频繁请求出错很正常，官方那边有限制，加上代理就行
