### ISSUE TITLE
如何在login页面同时显示注册按钮？

### ISSUE THREAD

**Issue by XxxoJun** [oddfar/campus-imaotai#124]
如何在login页面同时显示注册按钮？有办法实现吗

**Comment by ibycat** [comment]
同问

**Comment by Bet5521** [comment]
需要修改login.vue文件，在这个文件中91-94行，对注册按钮做了屏蔽。放开即可。
      // 验证码开关
      captchaEnabled: true,
      // 注册开关
      register: false,
