### ISSUE TITLE
发送验证码成功，但收不到短信验证码

### ISSUE THREAD

**Issue by Lasx** [oddfar/campus-imaotai#127]
发送验证码成功，但收不到短信验证码，无报错
[0;39m[33m2023-11-01 20:47:32[0;39m |[34mINFO [0;39m  |[34mIMTServiceImpl.java:126[0;39m |[36m「发送验证码返回」：{"code":2000}

**Comment by Lasx** [comment]
网络延迟有点厉害。。

**Comment by heyu3913** [comment]
解决了吗？我也收不到
