### ISSUE TITLE
看了下为什么旅行奖励不领取。但因为手机抓包有问题，也不清楚怎么修改

### ISSUE THREAD

**Issue by manBoooooooooooooom** [oddfar/campus-imaotai#130]
getXmTravelReward()这个函数以前应该是直接用于领取的，但是现在流程上似乎是不同了，变成了在点击领取奖励后是弹出了一个二级页来做一个确认动作(类似于一个刮刮乐一下，要自己刮一下，但是其实如果保持在这个界面不动，客户端会触发API动作，也会自动领取旅行奖励。)，所以我想应该是要改一下getXmTravelReward()这个函数中的接口地址和入参了。

**Comment by manBoooooooooooooom** [comment]
但不领取奖励似乎是不影响再次旅行的，可以自己手动在app上领取多次旅行奖励，具体是不是有其他问题就不是很清楚了。

**Comment by oddfar** [comment]
是的，app那边更新，本应用还没改
