### ISSUE TITLE
想问问用这个docker最低配置是多少g内存啊

### ISSUE THREAD

**Issue by Gnose** [oddfar/campus-imaotai#14]
启动redis直接退出了
WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition

**Comment by oddfar** [comment]
2G内存

**Comment by vcgg** [comment]
解决方案: echo 1 > /proc/sys/vm/overcommit_memory

**Comment by Gnose** [comment]
> 解决方案: echo 1 > /proc/sys/vm/overcommit_memory

要进入容器内执行吗

**Comment by vcgg** [comment]
> 

我之前也有遇到过这个，你直接在外面执行

**Comment by Gnose** [comment]
> > 
> 
> 我之前也有遇到过这个，你直接在外面执行

WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

改完报这个错，也改了这个还是一直报这错

**Comment by Gnose** [comment]
> net/core/somaxconn

net.core.somaxconn = 1024了还是报
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
也重载配置了~
