### ISSUE TITLE
刷新i茅台预约商品列表报错

### ISSUE THREAD

**Issue by Yaohongli** [oddfar/campus-imaotai#146]
![微信截图_20231207233748](https://github.com/oddfar/campus-imaotai/assets/153186736/4c4dc74e-f3f6-420a-8be2-f38ad1389043)

**Comment by oddfar** [comment]
JDK的AES加密异常java.security.InvalidKeyException: Illegal key size

jdk 1.8 去 https://www.oracle.com/java/technologies/javase-jce8-downloads.html 下载jar包

将压缩包中的两个jar包放在 %JDK_HOME%\jre\lib\security 目录下

引用：https://github.com/oddfar/campus-imaotai/issues/69
