### ISSUE TITLE
最新版本怎么确认位置信息

### ISSUE THREAD

**Issue by dz515704201** [oddfar/campus-imaotai#147]
现在的版本里预约的地点是怎样确定离我最近的地方的？预约门店选项可以多弄几个吗？因为有时候指定的单一门店当天没有可以预约的商品也是有可能的。另外有交流的地方吗？比如电报群

**Comment by oddfar** [comment]
参考： #117

**Comment by dz515704201** [comment]
谢谢大佬，我这边已经部署成功了。还有个问题是，我的环境是PVE下安装Ubuntu虚拟机，然后用docker-compose部署的，这个Ubuntu重启后，部署的这些项目没有自动启动起来。这个希望指导下，重启后怎么让其自动启动，而且这些docker有启动顺序要求吧

**Comment by oddfar** [comment]
> 谢谢大佬，我这边已经部署成功了。还有个问题是，我的环境是PVE下安装Ubuntu虚拟机，然后用docker-compose部署的，这个Ubuntu重启后，部署的这些项目没有自动启动起来。这个希望指导下，重启后怎么让其自动启动，而且这些docker有启动顺序要求吧

顺序只要campus-server在mysql redis服务之后启动就行
