### ISSUE TITLE
在arm平台openwrt里部署有问题

### ISSUE THREAD

**Issue by guochao00** [oddfar/campus-imaotai#149]
在arm平台openwrt里部署有问题，构建服务时会报错， 
=> [campus-mysql internal] load build definition from mysql-dockerfile                                                                                                                                  0.2s
 => => transferring dockerfile: 170B                                                                                                                                                                     0.0s
 => [campus-mysql internal] load .dockerignore                                                                                                                                                           0.2s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [campus-redis internal] load .dockerignore                                                                                                                                                           0.2s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [campus-redis internal] load build definition from redis-dockerfile                                                                                                                                  0.1s
 => => transferring dockerfile: 323B                                                                                                                                                                     0.0s
 => ERROR [campus-mysql internal] load metadata for docker.io/library/mysql:5.7                                                                                                                          2.6s
 => CANCELED [campus-redis internal] load metadata for docker.io/library/redis:latest                                                                                                                    2.7s
^Z ERROR [campus-mysql internal] load metadata for docker.io/library/mysql:5.7
[1]+  Stopped                 docker-compose build
不知道什么原因？
![微信图片_20231212200601](https://github.com/oddfar/campus-imaotai/assets/42381021/4a8971ec-afd1-42dd-b5d0-d97ca2ea887c)

**Comment by oddfar** [comment]
修改docker-compost.yml文件：services.campus-mysql下增加platform: linux/x86_64

参考：https://github.com/oddfar/campus-imaotai/issues/79
