### ISSUE TITLE
请问“用户id”对应为请求头中的什么数据？

### ISSUE THREAD

**Issue by fanfan142** [oddfar/campus-imaotai#15]

**Comment by fanfan142** [comment]
抓包deviceID后的值填入用户id，无法保存，提示：
JSON parse error: Cannot deserialize value of type `long` from String "C282D34E-2CD1-4979-8410-*********": not a valid `long` value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "C282D34E-2CD1-4979-8410-7A8BA52A6033": not a valid `long` value at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 34] (through reference chain: com.oddfar.campus.business.entity.IUser["userId"])
尝试改用MT-Requset-ID值无法预约，
日志为
{"message":"[ianus-token-auth] device id inconsistency","code":4011}

**Comment by oddfar** [comment]
用户id，在i茅台登录返回信息获取，对应字段`userId` ，IMTService接口中的 `login()`
请求头中，` request.header("userId", iUser.getUserId().toString());`
