### ISSUE TITLE
有没有大佬在服务器上搭建的教程？

### ISSUE THREAD

**Issue by Cyiming** [oddfar/campus-imaotai#154]
我是小白，有服务器，想参考别人的教程搭建下，但是很多问题不懂

1、java8怎么换成openjdk8能？没搜到这儿文件
2、user在哪行添加呢
![image](https://github.com/oddfar/campus-imaotai/assets/45073586/14f438d1-b567-4a13-b053-8ae93dff03b1)
……

**Comment by chensq666** [comment]
docker不香么

**Comment by 944196879** [comment]
> docker不香么

docker部署完，有用户注册账号功能吗？

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/releases/tag/V1.0.9
