### ISSUE TITLE
用docker部署完没有用户注册功能

### ISSUE THREAD

**Issue by 944196879** [oddfar/campus-imaotai#158]
用docker部署完没有用户注册功能，在系统设置里开启注册也不显示，也找不到配置文件

**Comment by oddfar** [comment]
有的，前端不显示跳转地址，但功能存在的，需要访问：`注册地址：/register` (参考文档)

**Comment by 944196879** [comment]
> 有的，前端不显示跳转地址，但功能存在的，需要访问： (参考文档)`注册地址：/register`

用这个链接确实可以注册，但是怎么在首页加上跳转注册呢？我研究一晚上重新打包了，但是没搞懂==。。。。

**Comment by oddfar** [comment]
> > 有的，前端不显示跳转地址，但功能存在的，需要访问： (参考文档)`注册地址：/register`
> 
> 用这个链接确实可以注册，但是怎么在首页加上跳转注册呢？我研究一晚上重新打包了，但是没搞懂==。。。。

这个就需要修改前端代码了，然后重新打包

**Comment by cjq6525** [comment]
> > > 有的，前端不显示跳转地址，但功能存在的，需要访问： (参考文档)`注册地址：/register`
> > 
> > 
> > 用这个链接确实可以注册，但是怎么在首页加上跳转注册呢？我研究一晚上重新打包了，但是没搞懂==。。。。
> 
> 这个就需要修改前端代码了，然后重新打包

具体需要修改哪部分能告知一下吗
