### ISSUE TITLE
使用IDEA里的Docker功能，编译运行报错，提示缺少./target/campus-modular.jar

### ISSUE THREAD

**Issue by arvinws** [oddfar/campus-imaotai#163]
Deploying '<unknown> Dockerfile: campus-modular/Dockerfile'…
Building image…
Preparing build context archive…
[==================================================>]59/59 files
Done

Sending build context to Docker daemon…
[==================================================>] 25.42kB
Done

Step 1/8 : FROM openjdk:8
 ---> b273004037cc
Step 2/8 : MAINTAINER oddfar
 ---> Running in 9c1b6416d8d3
Removing intermediate container 9c1b6416d8d3
 ---> 42444f078d32
Step 3/8 : RUN mkdir -p /home/campus/conf
 ---> Running in 21adce9ce2db
Removing intermediate container 21adce9ce2db
 ---> d2eb414d7e9d
Step 4/8 : WORKDIR /home/campus
 ---> Running in a6737bc4e5fa
Removing intermediate container a6737bc4e5fa
 ---> c189788eeb1e
Step 5/8 : ENV SERVER_PORT=8160
 ---> Running in e121ec6ebb0c
Removing intermediate container e121ec6ebb0c
 ---> adede8ea11f3
Step 6/8 : EXPOSE ${SERVER_PORT}
 ---> Running in e6ac38c96363
Removing intermediate container e6ac38c96363
 ---> f384aed44a61
Step 7/8 : ADD ./target/campus-modular.jar ./app.jar
Error response from daemon: ADD failed: file not found in build context or excluded by .dockerignore: stat target/campus-modular.jar: file does not exist
Failed to deploy '<unknown> Dockerfile: campus-modular/Dockerfile': Can't retrieve image ID from build stream

**Comment by oddfar** [comment]
需要先打包，选择prod环境，maven里的package install生成打包好的jar包，IDEA再根据jar包构建镜像。
具体百度参考教材，有很多的案例

**Comment by arvinws** [comment]
不是专门搞java的还真不会
