### ISSUE TITLE
东西是好东西，但是和宣称的“docker一键部署”的差距也太大了。。。

### ISSUE THREAD

**Issue by xanderma** [oddfar/campus-imaotai#164]
好不容易折腾完后端，结果一看前端部署还得自己搞ng，直接放弃。实在和宣称的“docker一键部署”有太大的差距，建议真实做一个一键部署脚本。

**Comment by oddfar** [comment]
看V1.0.8版本，一键docker启动了所有服务（包括redis、mysql、nginx前端）：https://github.com/oddfar/campus-imaotai/releases/tag/V1.0.8

V1.0.9后边改成了docker只启动后端，是因为有人服务器本来就有mysql了，再启动一个就造成了资源浪费。

但其实都一样的，无非就是写的Docker配置文件不一样。

**Comment by GGBOND1024** [comment]
大佬厉害
