### ISSUE TITLE
请教，按照视频部署前端未成功

### ISSUE THREAD

**Issue by Cyiming** [oddfar/campus-imaotai#166]
日志为
`. ____ _ __ _ _
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/ ___)| |_)| | | | | || (_| | ) ) ) )
' |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot :: (v2.5.15)

[33m2023-12-25 19:10:53[0;39m |[34mINFO [0;39m |[34mVersion.java:21[0;39m |[36mHV000001: Hibernate Validator 6.2.5.Final
[0;39m[33m2023-12-25 19:10:53[0;39m |[34mINFO [0;39m |[34mStartupInfoLogger.java:55[0;39m |[36mStarting CampusApplication using Java 1.8.0_371 on VM-8-8-debian with PID 374669 (/www/wwwroot/default/campus-modular.jar started by www in /www/wwwroot/default)
[0;39m[33m2023-12-25 19:10:53[0;39m |[39mDEBUG[0;39m |[34mStartupInfoLogger.java:56[0;39m |[36mRunning with Spring Boot v2.5.15, Spring v5.3.27
[0;39m[33m2023-12-25 19:10:53[0;39m |[34mINFO [0;39m |[34mSpringApplication.java:686[0;39m |[36mThe following 1 profile is active: "prod"
[0;39m[33m2023-12-25 19:10:58[0;39m |[31mWARN [0;39m |[34mAbstractApplicationContext.java:591[0;39m |[36mException encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'servletWebServerFactoryCustomizer' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.port' to java.lang.Integer
[0;39m[33m2023-12-25 19:10:58[0;39m |[1;31mERROR[0;39m |[34mLoggingFailureAnalysisReporter.java:40[0;39m |[36m

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.port' to java.lang.Integer:

Property: server.port
Value: 8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml
Origin: "server.port" from property source "commandLineArgs"
Reason: failed to convert java.lang.String to java.lang.Integer (caused by java.lang.NumberFormatException: For input string: "8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml")

Action:

Update your application's configuration

[0;39m
. ____ _ __ _ _
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/ ___)| |_)| | | | | || (_| | ) ) ) )
' |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot :: (v2.5.15)

[33m2023-12-25 19:14:18[0;39m |[34mINFO [0;39m |[34mVersion.java:21[0;39m |[36mHV000001: Hibernate Validator 6.2.5.Final
[0;39m[33m2023-12-25 19:14:18[0;39m |[34mINFO [0;39m |[34mStartupInfoLogger.java:55[0;39m |[36mStarting CampusApplication using Java 1.8.0_371 on VM-8-8-debian with PID 376487 (/www/wwwroot/default/campus-modular.jar started by www in /www/wwwroot/default)
[0;39m[33m2023-12-25 19:14:18[0;39m |[39mDEBUG[0;39m |[34mStartupInfoLogger.java:56[0;39m |[36mRunning with Spring Boot v2.5.15, Spring v5.3.27
[0;39m[33m2023-12-25 19:14:18[0;39m |[34mINFO [0;39m |[34mSpringApplication.java:686[0;39m |[36mThe following 1 profile is active: "prod"
[0;39m[33m2023-12-25 19:14:22[0;39m |[31mWARN [0;39m |[34mAbstractApplicationContext.java:591[0;39m |[36mException encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'servletWebServerFactoryCustomizer' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.port' to java.lang.Integer
[0;39m[33m2023-12-25 19:14:22[0;39m |[1;31mERROR[0;39m |[34mLoggingFailureAnalysisReporter.java:40[0;39m |[36m

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.port' to java.lang.Integer:

Property: server.port
Value: 8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml
Origin: "server.port" from property source "commandLineArgs"
Reason: failed to convert java.lang.String to java.lang.Integer (caused by java.lang.NumberFormatException: For input string: "8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml")

Action:

Update your application's configuration

[0;39m
. ____ _ __ _ _
/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/ ___)| |_)| | | | | || (_| | ) ) ) )
' |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot :: (v2.5.15)

[33m2023-12-25 19:20:46[0;39m |[34mINFO [0;39m |[34mVersion.java:21[0;39m |[36mHV000001: Hibernate Validator 6.2.5.Final
[0;39m[33m2023-12-25 19:20:46[0;39m |[34mINFO [0;39m |[34mStartupInfoLogger.java:55[0;39m |[36mStarting CampusApplication using Java 1.8.0_371 on VM-8-8-debian with PID 378650 (/www/wwwroot/default/campus-modular.jar started by www in /www/wwwroot/default)
[0;39m[33m2023-12-25 19:20:47[0;39m |[39mDEBUG[0;39m |[34mStartupInfoLogger.java:56[0;39m |[36mRunning with Spring Boot v2.5.15, Spring v5.3.27
[0;39m[33m2023-12-25 19:20:47[0;39m |[34mINFO [0;39m |[34mSpringApplication.java:686[0;39m |[36mThe following 1 profile is active: "prod"
[0;39m[33m2023-12-25 19:20:50[0;39m |[31mWARN [0;39m |[34mAbstractApplicationContext.java:591[0;39m |[36mException encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'servletWebServerFactoryCustomizer' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.port' to java.lang.Integer
[0;39m[33m2023-12-25 19:20:50[0;39m |[1;31mERROR[0;39m |[34mLoggingFailureAnalysisReporter.java:40[0;39m |[36m

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.port' to java.lang.Integer:

Property: server.port
Value: 8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml
Origin: "server.port" from property source "commandLineArgs"
Reason: failed to convert java.lang.String to java.lang.Integer (caused by java.lang.NumberFormatException: For input string: "8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml")

Action:

Update your application's configuration

[0;39m`

加的代码看着视频敲的不知道对不对
`--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml`
![image](https://github.com/oddfar/campus-imaotai/assets/45073586/d8ebf016-4c6c-4da0-b24d-cb667aaee268)

**Comment by oddfar** [comment]
8160后边要加个空格 server.port=8160 --Dspring......

**Comment by oddfar** [comment]
没连接到数据库，可能配置文件没写对，或者引入的地址不对
`--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml`
/www/wwwroot/campus-imaotai 是文件所在的目录
