### ISSUE TITLE
添加系统用户出现几个小bug

### ISSUE THREAD

**Issue by arvinws** [oddfar/campus-imaotai#168]
![image](https://github.com/oddfar/campus-imaotai/assets/43133223/2ee48907-0703-4ae9-9dd7-39d6596d4136)
![image](https://github.com/oddfar/campus-imaotai/assets/43133223/334b14b0-0ef9-4830-9acf-c169180c1f65)
![image](https://github.com/oddfar/campus-imaotai/assets/43133223/10a7e1e5-a203-400d-947f-c149bc7a882a)

1.角色不加载
2.点新增不填信息又加载出来了
3.所有信息填完，保存报错

**Comment by oddfar** [comment]
请使用 `V1.0.11` 版本
