### ISSUE TITLE
用户权限出现bug

### ISSUE THREAD

**Issue by 944196879** [oddfar/campus-imaotai#169]
新增i茅台角色用户，登进去无法添加账号，提示没有权限，超级管理员进去管理i茅台权限提示未知错误

**Comment by oddfar** [comment]
检查版本，使用`V1.0.11`。
初始角色 “i茅台” 只有查询日志的权限，其他权限需要自己手动给予

![WeChata3efbacd4187c75483cd5df280c6d4d4](https://github.com/oddfar/campus-imaotai/assets/76616434/9df728e4-89b5-42dc-9ba9-aeadb7588d3d)

**Comment by 944196879** [comment]
> 检查版本，使用`V1.0.11`。初始角色“我茅台"只有查询日志的权限,其他权限需要自己手动给予
> 
> ![WeChata3efbacd4187c75483cd5df280c6d4d4](https://private-user-images.githubusercontent.com/76616434/292953855-9df728e4-89b5-42dc-9ba9-aeadb7588d3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTE4MjgsIm5iZiI6MTcwMzY1MTUyOCwicGF0aCI6Ii83NjYxNjQzNC8yOTI5NTM4NTUtOWRmNzI4ZTQtODliNS00MmRjLTliYTktYWVhZGI3NTg4ZDNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA0MzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTAzYmUyMWQ5ODhiOGRmNzZmMjNmMDUyYmUxOWRiMzM3NTcyOTExM2ZlNTMxODMzOWEzNzMzMzI5Njc5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5krA7acSTh1tZdHzoplWo0QPooKxzEEfDIM34v6UX0)

![Screenshot_20231227_123109_com tencent mtt](https://github.com/oddfar/campus-imaotai/assets/149235500/1a05d12b-e410-4d7c-ba53-25fa4b45516b)
修改权限提示系统未知错误

**Comment by oddfar** [comment]
刚用全新的环境，重新搭建了一遍，没有复现出你的问题

**Comment by 944196879** [comment]
> 刚用全新的环境，重新搭建了一遍，没有复现出你的问题

我是从1.0.9升上来的，docker后端容器升完没出现端口号，是不是和这有关？

**Comment by oddfar** [comment]
> > 刚用全新的环境，重新搭建了一遍，没有复现出你的问题
> 
> 我是从1.0.9升上来的，docker后端容器升完没出现端口号，是不是和这有关？

应该不是，看下 `docker logs 容器id` 日志报错什么

**Comment by 944196879** [comment]
> > > 刚用全新的环境，重新搭建了一遍，没有复现出你的问题
> > 
> > 
> > 我是从1.0.9升上来的，docker后端容器升完没出现端口号，是不是和这有关？
> 
> 应该不是，看下 `docker logs 容器id` 日志报错什么

我把日志清空重启容器后又好了，真的时奇奇怪怪
