### ISSUE TITLE
这是啥问题呢。

### ISSUE THREAD

**Issue by m511386374** [oddfar/campus-imaotai#17]
![image](https://github.com/oddfar/campus-imaotai/assets/19544200/23166d6a-2147-42ae-ba4b-377202c66629)

**Comment by oddfar** [comment]
把你的账号配置内容截图一下，手机号等关键信息打码，可能是预约的code更新了

**Comment by m511386374** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/19544200/6f4d28b2-3230-4473-a1bf-20f6b5cfb605)

**Comment by oddfar** [comment]
省份 城市没填对，看说明，例如： 河北省，石家庄市

**Comment by WnoteZZ** [comment]
![77a64555e693f4a896e49070505096a](https://github.com/oddfar/campus-imaotai/assets/31717410/79453f98-6764-4ce1-a4bf-49edf368dffc)

**Comment by oddfar** [comment]
> debug了一下 链接 [https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/683/河南省/10213/1689177600000](https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/683/%E6%B2%B3%E5%8D%97%E7%9C%81/10213/1689177600000) ![77a64555e693f4a896e49070505096a](https://user-images.githubusercontent.com/31717410/253223511-dea897c9-b56f-4ece-9382-ac9bd7366b7a.png) ![image](https://user-images.githubusercontent.com/31717410/253223838-bf396518-aa9b-40c0-9222-6b08d87f1092.png)

[https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/685/河南省/10213/1689177600000](https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/685/%E6%B2%B3%E5%8D%97%E7%9C%81/10213/1689177600000)

今天的是685，683换成685就行了。
redis缓存没更新key：`mt_session_id`，会在每天9点自动刷新：`CampusIMTTask`

**Comment by hcliu987** [comment]
我这个代码改了下，有效时间 3 小时
