### ISSUE TITLE
[bug]: 你的打包我真看不懂，大佬我看你教程操作了六个小时，太乱了你的教程

### ISSUE THREAD

**Issue by ansomeck** [oddfar/campus-imaotai#170]
什么都解决了，看到你这个教程这里真的不适合新手
你这打包我是在服务器打包还是什么呢？

打包
命令如下：

# 打包正式环境
npm run build:prod

# 打包预发布环境
npm run build:stage
包成功之后，会在根目录生成 dist 文件夹，里面就是构建打包好的文件

这个在服务器运行都是出错的
真的很懵

**Comment by oddfar** [comment]
新手建议用docker启动所有服务
