### ISSUE TITLE
部署成功，但是所有接口全部报错401，包括登录和获取验证码

### ISSUE THREAD

**Issue by mogody** [oddfar/campus-imaotai#173]
## 版本情况

campus框架版本： 1.0.11

本项目campus-imaotai版本： 1.0.11

## 问题描述
按照文档，使用docker部署成功，但是所有接口报错401

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

## 问题内容（如有）

<img width="701" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/10496478/11ffa93b-6cc0-4bb8-b3fe-d7301782bbc1">

**Comment by webees** [comment]
我在集群中进行了部署，有同样的问题，楼主怎么解决的？
