### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by lingganwu** [oddfar/campus-imaotai#175]
## 版本情况

campus框架版本：1.1.9

本项目campus-imaotai版本：1.0.11

## 问题描述
搭建完成之后出现这个提示！
![screenshot20240107](https://github.com/oddfar/campus-imaotai/assets/59476145/5c391d6f-4161-488e-83d7-b30af4d9b1b5)

**Comment by CHANGLERCN** [comment]
我前几天还都正常 就今天和你报错一样 肯定是官方换接口了

**Comment by oddfar** [comment]
今天版本龙茅，需要把item_code字段改一下10213@10214@  --> 10941@10942@
