### ISSUE TITLE
登录web页面后台，没有i茅台菜单选项

### ISSUE THREAD

**Issue by wxz8506** [oddfar/campus-imaotai#176]
根据B站视频教程和centos7环境+宝塔面板设置的。
登录web页面后台，但是没有i茅台菜单选项，请问是什么原因？
![企业微信截图_17046306494273](https://github.com/oddfar/campus-imaotai/assets/24426543/d3a79223-d85c-4212-858c-9a3fcb99e0cf)

**Comment by oddfar** [comment]
数据库没导入全或者导错了，选择5.7版本或以上

**Comment by heyu3913** [comment]
> 根据B站视频教程和centos7环境+宝塔面板设置的。 登录web页面后台，但是没有i茅台菜单选项，请问是什么原因？ ![企业微信截图_17046306494273](https://private-user-images.githubusercontent.com/24426543/294757911-d3a79223-d85c-4212-858c-9a3fcb99e0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODE5OTQsIm5iZiI6MTcyNjI4MTY5NCwicGF0aCI6Ii8yNDQyNjU0My8yOTQ3NTc5MTEtZDNhNzkyMjMtZDg1Yy00MjEyLTg1OGMtOWEzZmNiOTllMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhM2ZjYjJjMjJjNjllMGYyNWE0OTUzNTUzMWJjMWYxOTY3NDY1NTBmMjY0ZTgzNDk5MGVjYmM0MWMxNmQxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v69p0VbCW3CCtZMuqODwZqXTQJNUHQ2sKi5RH9BhoQs)

哥们 这个问题你解决了吗？我也出现了这个问题
