### ISSUE TITLE
搭建好第二天，验证码显示不出来，报错如下：

### ISSUE THREAD

**Issue by wangkangfeng1999** [oddfar/campus-imaotai#18]
![image](https://github.com/oddfar/campus-imaotai/assets/68324194/bc06533d-6c77-4ffc-8717-76f53a9b6b70)

**Comment by oddfar** [comment]
这种情况就是redis被黑了，因为没设密码
解决方案：`安全组添加禁止访问6379端口` 或 `6379改成别的端口号`

**Comment by wangkangfeng1999** [comment]
> 这种情况就是redis被黑了，因为没设密码 解决方案：`安全组添加禁止访问6379端口` 或 `6379改成别的端口号`

修改端口需要改哪些地方

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
> 修改 docker-compose.yml 里的端口配置，例如 MySql：3306:3306 改成 3307:3306
