### ISSUE TITLE
[bug]: campus-server无法连接mysql，并且自动退出

### ISSUE THREAD

**Issue by SamSunChan** [oddfar/campus-imaotai#185]
部署的是[V1.0.11](https://github.com/oddfar/campus-imaotai/releases/tag/V1.0.11)

docker-compose up -d执行完之后，发现campus-server启动一会后会停止运行，等mysql执行一段时间后，重新执行docker-compose up -d情况一样，执行docker logs -f campus-server查看日志，发现以下错误：

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

com.mysql.cj.exceptions.CJException: null,  message from server: "Host '172.22.0.4' is not allowed to connect to this MySQL server"

部署了多次，也清理过之前的容器和镜像重新部署。都不行。

另外，访问页面，不显示验证码，估计也和这个有关系吧。

**Comment by snapea** [comment]
您遇到的错误 java.sql.SQLNonTransientConnectionException: Could not create connection to database server. 以及来自服务器的具体信息 "Host '172.22.0.4' is not allowed to connect to this MySQL server" 表明您尝试从 IP 地址 172.22.0.4 连接到 MySQL 数据库服务器时，连接被拒绝了。

这个问题通常是由于 MySQL 数据库的用户权限配置不允许来自该 IP 地址的连接。为了解决这个问题，您需要执行以下步骤：

登录到 MySQL 服务器：
使用具有足够权限的用户登录到 MySQL 服务器。通常，这需要 root 用户或具有修改用户权限的其他用户。

检查用户权限：
查看当前用户的权限，确保该用户有权从指定的 IP 地址或任意主机连接。您可以使用以下命令查看用户的主机权限：
```sh
SELECT user, host FROM mysql.user;
```
更新用户权限：
如果用户没有从 172.22.0.4 连接的权限，您需要更新用户权限。这可以通过授予用户从该 IP 地址连接的权限来完成。例如，如果您的用户是 yourusername 并且您希望允许从任何主机连接，可以使用以下命令：
```sh
GRANT ALL PRIVILEGES ON yourdatabase.* TO 'yourusername'@'%' IDENTIFIED BY 'yourpassword';
FLUSH PRIVILEGES;
```
如果您只想允许来自特定 IP 地址的连接，将 '%' 替换为 '172.22.0.4'。

检查防火墙设置：
确保没有防火墙规则阻止从 IP 地址 172.22.0.4 到 MySQL 服务器的连接。如果存在防火墙，您需要更新规则以允许这些连接。

检查 MySQL 绑定地址：
MySQL 服务器可以配置为只监听来自特定网络接口的连接。这是通过 bind-address 配置在 my.cnf 或 mysqld.cnf 文件中完成的。确保它不是设置为仅监听本地连接（例如 127.0.0.1 或 localhost）。

重启 MySQL 服务：
在更改权限或配置文件后，您可能需要重启 MySQL 服务以使更改生效。

执行这些步骤应该能够解决您的连接问题。如果问题仍然存在，可能需要进一步检查您的数据库配置和网络设置。

**Comment by SamSunChan** [comment]
> 您遇到的错误 java.sql.SQLNonTransientConnectionException: Could not create connection to database server. 以及来自服务器的具体信息 "Host '172.22.0.4' is not allowed to connect to this MySQL server" 表明您尝试从 IP 地址 172.22.0.4 连接到 MySQL 数据库服务器时，连接被拒绝了。
> 
> 这个问题通常是由于 MySQL 数据库的用户权限配置不允许来自该 IP 地址的连接。为了解决这个问题，您需要执行以下步骤：
> 
> 登录到 MySQL 服务器： 使用具有足够权限的用户登录到 MySQL 服务器。通常，这需要 root 用户或具有修改用户权限的其他用户。
> 
> 检查用户权限： 查看当前用户的权限，确保该用户有权从指定的 IP 地址或任意主机连接。您可以使用以下命令查看用户的主机权限：
> 
> ```shell
> SELECT user, host FROM mysql.user;
> ```
> 
> 更新用户权限： 如果用户没有从 172.22.0.4 连接的权限，您需要更新用户权限。这可以通过授予用户从该 IP 地址连接的权限来完成。例如，如果您的用户是 yourusername 并且您希望允许从任何主机连接，可以使用以下命令：
> 
> ```shell
> GRANT ALL PRIVILEGES ON yourdatabase.* TO 'yourusername'@'%' IDENTIFIED BY 'yourpassword';
> FLUSH PRIVILEGES;
> ```
> 
> 如果您只想允许来自特定 IP 地址的连接，将 '%' 替换为 '172.22.0.4'。
> 
> 检查防火墙设置： 确保没有防火墙规则阻止从 IP 地址 172.22.0.4 到 MySQL 服务器的连接。如果存在防火墙，您需要更新规则以允许这些连接。
> 
> 检查 MySQL 绑定地址： MySQL 服务器可以配置为只监听来自特定网络接口的连接。这是通过 bind-address 配置在 my.cnf 或 mysqld.cnf 文件中完成的。确保它不是设置为仅监听本地连接（例如 127.0.0.1 或 localhost）。
> 
> 重启 MySQL 服务： 在更改权限或配置文件后，您可能需要重启 MySQL 服务以使更改生效。
> 
> 执行这些步骤应该能够解决您的连接问题。如果问题仍然存在，可能需要进一步检查您的数据库配置和网络设置。

我是用campus-imt-V1.0.11.tar一键脚本部署的，应该不会出现这类问题吧？说明文档里也没说需要配置mysql 。另外，项目里的mysql的password是多少？

**Comment by chibinyong** [comment]
campus-imt-V1.0.11.tar一键脚本部署 同样出现这个问题

**Comment by 2022ctrl** [comment]
> > 您遇到的错误 java.sql.SQLNonTransientConnectionException: Could not create connection to database server. 以及来自服务器的具体信息 "Host '172.22.0.4' is not allowed to connect to this MySQL server" 表明您尝试从 IP 地址 172.22.0.4 连接到 MySQL 数据库服务器时，连接被拒绝了。
> > 这个问题通常是由于 MySQL 数据库的用户权限配置不允许来自该 IP 地址的连接。为了解决这个问题，您需要执行以下步骤：
> > 登录到 MySQL 服务器： 使用具有足够权限的用户登录到 MySQL 服务器。通常，这需要 root 用户或具有修改用户权限的其他用户。
> > 检查用户权限： 查看当前用户的权限，确保该用户有权从指定的 IP 地址或任意主机连接。您可以使用以下命令查看用户的主机权限：
> > ```shell
> > SELECT user, host FROM mysql.user;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更新用户权限： 如果用户没有从 172.22.0.4 连接的权限，您需要更新用户权限。这可以通过授予用户从该 IP 地址连接的权限来完成。例如，如果您的用户是 yourusername 并且您希望允许从任何主机连接，可以使用以下命令：
> > ```shell
> > GRANT ALL PRIVILEGES ON yourdatabase.* TO 'yourusername'@'%' IDENTIFIED BY 'yourpassword';
> > FLUSH PRIVILEGES;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果您只想允许来自特定 IP 地址的连接，将 '%' 替换为 '172.22.0.4'。
> > 检查防火墙设置： 确保没有防火墙规则阻止从 IP 地址 172.22.0.4 到 MySQL 服务器的连接。如果存在防火墙，您需要更新规则以允许这些连接。
> > 检查 MySQL 绑定地址： MySQL 服务器可以配置为只监听来自特定网络接口的连接。这是通过 bind-address 配置在 my.cnf 或 mysqld.cnf 文件中完成的。确保它不是设置为仅监听本地连接（例如 127.0.0.1 或 localhost）。
> > 重启 MySQL 服务： 在更改权限或配置文件后，您可能需要重启 MySQL 服务以使更改生效。
> > 执行这些步骤应该能够解决您的连接问题。如果问题仍然存在，可能需要进一步检查您的数据库配置和网络设置。
> 
> 我是用campus-imt-V1.0.11.tar一键脚本部署的，应该不会出现这类问题吧？说明文档里也没说需要配置mysql 。另外，项目里的mysql的password是多少？

我使用的docker部署，倒是没有遇到这个问题，手动建立数据库，mysql版本需要8 然后开启服务器的3306，远程连接服务器的数据库，执行作者提供的SQL脚本，就完事了，然后修改yml文件。密码去宝塔里看，改成自己服务器的数据库密码

**Comment by SamSunChan** [comment]
已解决：sql配置数据库权限就正常了。另外：后续重新部署了N个环境也不存在这个问题。

**Comment by Jameslai93** [comment]
> 已解决：sql配置数据库权限就正常了。另外：后续重新部署了N个环境也不存在这个问题。

怎么解决这个问题
