### ISSUE TITLE
[bug]: docker 镜像拉去不了

### ISSUE THREAD

**Issue by mawenbin666** [oddfar/campus-imaotai#188]
docker 镜像拉去不了啊
[root@VM-20-9-centos docker]# docker pull oddfar/campus-imaotai
Using default tag: latest
Trying to pull repository docker.io/oddfar/campus-imaotai ...

Get https://registry-1.docker.io/v2/oddfar/campus-imaotai/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Aoddfar%2Fcampus-imaotai%3Apull&service=registry.docker.io: net/http: TLS handshake timeout

**Comment by oddfar** [comment]
镜像切成国内的试试
