### ISSUE TITLE
有点问题，不知道商品那路径错了

### ISSUE THREAD

**Issue by student-12k** [oddfar/campus-imaotai#19]
![1689304972551](https://github.com/oddfar/campus-imaotai/assets/27775869/34b0a892-9985-4053-aa27-c5554f1fa308)

**Comment by student-12k** [comment]
/
![1689304795145](https://github.com/oddfar/campus-imaotai/assets/27775869/6092ab9f-c732-49c6-9c0e-440aad1300d4)
![1689304836619](https://github.com/oddfar/campus-imaotai/assets/27775869/71702790-04c3-410c-9894-8405c21c6fca)

**Comment by oddfar** [comment]
看看是不是配置没写对：https://github.com/oddfar/campus-imaotai/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8#%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8
> 注意⚠️ 省份和城市需填完整的，例如 河北省，石家庄市

**Comment by student-12k** [comment]
重新部署就好了，应该是redis里面数据掉了
