### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by 00660** [oddfar/campus-imaotai#191]
Step 4/7 : RUN mkdir -p /home/campus
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 98c1da59097f
exec /bin/sh: exec format error
ERROR: Service 'campus-server' failed to build: The command '/bin/sh -c mkdir -p /home/campus' returned a non-zero code: 1

**Comment by oddfar** [comment]
arm参考其他人解决方案
