### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Rxout** [oddfar/campus-imaotai#195]
一建docker 的时候 为什么会报这个错呢 ，这个错有解决办法吗。
 => ERROR [campus-server internal] load metadata for docker.io/library/java:8                                                             2.7s
------
 > [campus-server internal] load metadata for docker.io/library/java:8:
------
failed to solve: java:8: docker.io/library/java:8: not found

**Comment by oddfar** [comment]
重复问题
