### ISSUE TITLE
[bug]: mysql:5.7 从 docker 上已经获取不到了

### ISSUE THREAD

**Issue by weili80** [oddfar/campus-imaotai#205]
## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： X.X.X（请确保最新尝试是否还有问题）

## 问题描述

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```
5.7: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
3. 测试涉及到的文件（如有）

**Comment by oddfar** [comment]
重复问题，arm64的，搜issues其他人的解决方案

**Comment by weili80** [comment]
我电脑 m2 cpu. #79 的方法是了没用。

**Comment by oddfar** [comment]
> 我电脑 m2 cpu. #79 的方法试了没用。

根据报错内容具体参考百度解决方案
