### ISSUE TITLE
[bug]: 作者大大能不能分享个青龙一件脚本地址？

### ISSUE THREAD

**Issue by chuanyuehuoxian8** [oddfar/campus-imaotai#206]
## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： X.X.X（请确保最新尝试是否还有问题）

## 问题描述

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

**Comment by jjwjs** [comment]
不是青龙版本的

**Comment by chuanyuehuoxian8** [comment]
谢谢

**Comment by oddfar** [comment]
https://github.com/yize8888/maotai
