### ISSUE TITLE
什么是门店商品ID？

### ISSUE THREAD

**Issue by LucienShui** [oddfar/campus-imaotai#207]
翻遍了 issue 和文档也没搜到这个怎么获取，在客户端里找了一圈也没找到。

**Comment by jjwjs** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/94659625/35c4df9b-451a-443d-a1e3-758c68c41b77)
这就是

**Comment by LucienShui** [comment]
@jjwjs 非常感谢！
