### ISSUE TITLE
docker-compose up -d 时报错

### ISSUE THREAD

**Issue by LinkStark** [oddfar/campus-imaotai#21]
![image](https://github.com/oddfar/campus-imaotai/assets/83204736/86975660-8583-47dd-b7d3-a982cfba9daf)
报错如上，百度搜不到解决方法，环境是win7+docker toolbox，输入docker-compose up -d后最后报错，请问有解决办法吗

**Comment by oddfar** [comment]
报错内容显示，创建的linux版redis，win用不了
坐等客户端版本吧

**Comment by LinkStark** [comment]
> 报错内容显示，创建的linux版redis，win用不了 坐等客户端版本吧

好的，谢谢大佬
