### ISSUE TITLE
[bug]:出现 ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by caojjyy** [oddfar/campus-imaotai#215]
![问题](https://github.com/oddfar/campus-imaotai/assets/70875729/f1277594-ea1a-4383-bc7c-07e89a5f71d0)

## 版本情况

campus框架版本：1.1.9（不知道可不填）

本项目campus-imaotai版本：1.0.11（请确保最新尝试是否还有问题）

## 问题描述

部署好了之后出现这个报错，应该怎么处理呢

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

**Comment by oddfar** [comment]
百度一下，参考网上教程
