### ISSUE TITLE
[bug]: 本地运行 添加用户的时候提升获取验证码失败

### ISSUE THREAD

**Issue by hangzhouljp** [oddfar/campus-imaotai#220]
![image](https://github.com/oddfar/campus-imaotai/assets/38392441/fb6093df-f4e4-4505-89cc-26f4f5d45abb)

**Comment by Re-Cwer** [comment]
我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。

**Comment by lkeai2007** [comment]
多按几次，我的就是这样

**Comment by Re-Cwer** [comment]
找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://github.com/oddfar/campus-imaotai/assets/78371395/88d700c4-7446-4d64-a631-d0d4d99f409d)

**Comment by SamSunChan** [comment]
> 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。

请问arm32用的是哪个jdk镜像？

**Comment by Re-Cwer** [comment]
JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> 
> 
> 请问arm32用的是哪个jdk镜像？

**Comment by Re-Cwer** [comment]
Jdk你可以到jdk官网上下载选择对应的处理器的包就可以了，我是本地部署的，因为我服务器太差了并没有用docker部署> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> 
> 
> 请问arm32用的是哪个jdk镜像？

**Comment by SamSunChan** [comment]
> JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> > 请问arm32用的是哪个jdk镜像？

我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。

我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。

**Comment by Re-Cwer** [comment]
Docker我不懂如何打包，你可以看我上面发的图片，改一下代码。如果你是本地运行的我可以发我打包好的jar包给你用> > JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> > 
> 
> > > 请问arm32用的是哪个jdk镜像？
> 
> 
> 
> 我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。
> 
> 
> 
> 我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。

**Comment by Re-Cwer** [comment]
你可以去官网下一下这个，我用的是这个。jdk-8u191-linux-arm32-vfp-hflt.tar.gz> > JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> > 
> 
> > > 请问arm32用的是哪个jdk镜像？
> 
> 
> 
> 我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。
> 
> 
> 
> 我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。

**Comment by Re-Cwer** [comment]
> > JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> 
> > 
> 
> > > 请问arm32用的是哪个jdk镜像？
> 
> 
> 
> 我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。
> 
> 
> 
> 我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。

玩客云不建议使用docker性能太弱了

**Comment by sanmuhub** [comment]
> > JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> > > 请问arm32用的是哪个jdk镜像？
> 
> 我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。
> 
> 我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。

我玩客云，mysql，Redis，都ok，不卡，仓库里镜像不是armV7，我也不会其他打包方式，所以就暂时搁着了。。

**Comment by sanmuhub** [comment]
> > > JDK1.8,我昨晚排查了一下，并不是jdk的问题，是代码的问题，需要改一下代码才可以，因为可能是cpu太弱鸡了，运行太慢了，导致md5的加密时间，发送的时间戳相差太大导致的。> > 我也遇到了这个问题，在自己的电脑运行jar包没问题，在idea中运行也没问题，放在Debian上就出现了这个问题。我的cpu处理器是arm32位的。目前还不知道啥原因。
> > > > 请问arm32用的是哪个jdk镜像？
> > 
> > 
> > 我J1900，也会存在短信验证码的问题，用你的方法解决了，证明不是你CPU性能弱的问题。
> > 我问你armv7用哪个jdk是因为刚好有个玩客云，也试着部署下，由于armv7问题，我docker换了mysql和jdk，部署好后，armv7启动要接近20分钟，超级慢。J1900启动1分钟不到。
> 
> 我玩客云，mysql，Redis，都ok，不卡，仓库里镜像不是armV7，我也不会其他打包方式，所以就暂时搁着了。。

The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Comment by Re-Cwer** [comment]
可以的> > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> 
> 
> 
> 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299

**Comment by SamSunChan** [comment]
> > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> 
> 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299

去我的仓库下载一个就行了，我修正了这个BUG，也编译了个包提供大家下载

**Comment by sanmuhub** [comment]
> > > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> > 
> > 
> > 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299
> 
> 去我的仓库下载一个就行了，我修正了这个BUG，也编译了个包提供大家下载

哥们儿，你改了admin默认密码？还放在包里。。。硬猜啊你让我

**Comment by sanmuhub** [comment]
加了这句命令也不行。。jar后端，armV7处理器

**Comment by wangshaoce** [comment]
> > > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> > 
> > 
> > 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299
> 
> 去我的仓库下载一个就行了，我修正了这个BUG，也编译了个包提供大家下载
默认密码修改回来了按摩

**Comment by SamSunChan** [comment]
> > > > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> > > 
> > > 
> > > 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299
> > 
> > 
> > 去我的仓库下载一个就行了，我修正了这个BUG，也编译了个包提供大家下载
> 
> 哥们儿，你改了admin默认密码？还放在包里。。。硬猜啊你让我

密码和包有啥关系？我是直接拿oddfar的改了编译的，密码是在mysql数据库里设置的，你是自己之前改了忘记了吧？

**Comment by SamSunChan** [comment]
> > > > 找到问题了，获取短信的接口，m5里面的时间，与请求头的时间不一致，导致的报错，定义一个时间戳变量给请求头与m5就可以了，![image](https://private-user-images.githubusercontent.com/78371395/297123802-88d700c4-7446-4d64-a631-d0d4d99f409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODUyODAsIm5iZiI6MTcwNjE4NDk4MCwicGF0aCI6Ii83ODM3MTM5NS8yOTcxMjM4MDItODhkNzAwYzQtNzQ0Ni00ZDY0LWE2MzEtZDBkNGQ5OWY0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWI1YzQyODViNWQzNjRkYmIxNGMyOWRhOWE1N2ZhODdiNWUzOTJkNzJmOGY2MTY1MDEyYmY2YTRkYzBkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1cdachEHmvp95rR4JXXX_HLflFrs71oJvKpRDiKgZk)
> > > 
> > > 
> > > 大佬，求分享改好的包-不懂java 实在是搞不了。跪求。QQ272778299
> > 
> > 
> > 去我的仓库下载一个就行了，我修正了这个BUG，也编译了个包提供大家下载
> > 默认密码修改回来了吗

我只编译了包，又没动mysql，密码是在mysql数据库里的，不要被人误导，直接用我的包替换掉jar包，重启后就可以解决短信问题了
