### ISSUE TITLE
[bug]: 有计划增加自动收取7天、14天、28天小茅运功能么？

### ISSUE THREAD

**Issue by huangdongliang** [oddfar/campus-imaotai#227]
## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： X.X.X（请确保最新尝试是否还有问题）

## 问题描述

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

**Comment by oddfar** [comment]
![1](https://github.com/oddfar/campus-imaotai/assets/76616434/813ef3f3-9bc5-42fc-bcee-5f522300fd51)
<img width="604" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/7ffc6a0c-f7b8-4778-a7e8-f9d64b51dcab">

**Comment by huangdongliang** [comment]
1、首先感谢作者大大免费开源这个优秀的项目出来。
2、表示我能看懂你的请求，和返回对应的参数结果，我本人不会开发。
3、是否有计划以后会增加这个功能那？

**Comment by oddfar** [comment]
> 1、首先感谢作者大大免费开源这个优秀的项目出来。 2、表示我能看懂你的请求，和返回对应的参数结果，我本人不会开发。 3、是否有计划以后会增加这个功能那？

不一定

**Comment by huangdongliang** [comment]
感谢
