### ISSUE TITLE
[bug]: InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by tysong1** [oddfar/campus-imaotai#228]
![image](https://github.com/oddfar/campus-imaotai/assets/13828087/e0366b6e-898e-41ad-9a4d-0e24cfd7a25d)

## 版本情况

campus框架版本： 1.1.9（不知道可不填）

本项目campus-imaotai版本： 1.0.11（请确保最新尝试是否还有问题）

## 问题描述

1. 使用的什么功能
自动预约，提示三方范围有问题
2. 复现代码（如有）

```java
[结果返回]：InvalidKeyException: Illegal key size
```

3. 测试涉及到的文件（如有）

## 问题内容（如有）

![image](https://github.com/oddfar/campus-imaotai/assets/13828087/9776250e-50ed-4e39-b3c3-063541de9599)

**Comment by cherl** [comment]
怎么解决的呀？我也是这个问题
