### ISSUE TITLE
貌似1.012版本没上传到dockerhub上呀

### ISSUE THREAD

**Issue by Tandent-zz** [oddfar/campus-imaotai#231]
在dockerhub上看见的还是1.0.11版本，版主可否更新一下dockerhub
![1705889284996](https://github.com/oddfar/campus-imaotai/assets/16612843/1af6c9e0-f61d-45e3-9f51-320d1a7d8846)

**Comment by oddfar** [comment]
没传呢，后边配下docker hub的自动构建
