### ISSUE TITLE
[bug]: 门店列表菜单里，刷新按钮名称应该是“刷新门店列表”，1.0.12是“刷新i茅台商品列表”

### ISSUE THREAD

**Issue by sanmuhub** [oddfar/campus-imaotai#233]
## 版本情况

campus框架版本：1.1.9（不知道可不填）

本项目campus-imaotai版本： 1.0.12（请确保最新尝试是否还有问题）

## 问题描述

<门店列表菜单>

1. 门店列表菜单刷新

2. 刷新按钮名称应该是“刷新门店列表”，1.0.12是“刷新i茅台商品列表”
![Uploading 微信截图_20240122215128.png…]()

**Comment by oddfar** [comment]
图片看不了

**Comment by sanmuhub** [comment]
![微信截图_20240122001403](https://github.com/oddfar/campus-imaotai/assets/157190776/6e9bd967-78fb-4f8d-89c7-0dd60dc5bb0e)


> 图片看不了

**Comment by sanmuhub** [comment]
> 图片看不了

![微信截图_20240123002202](https://github.com/oddfar/campus-imaotai/assets/157190776/28bc2da2-15de-4ac2-9dc4-dfd387aefffe)
上传有点儿慢，发表点的早了

**Comment by oddfar** [comment]
返回字段为 shopId 翻译成商品ID了，小问题，怎么理解都行
