### ISSUE TITLE
手动点击预约报错[bug]: 

### ISSUE THREAD

**Issue by huangdongliang** [oddfar/campus-imaotai#235]
## 版本情况

campus框架版本： v1.0.11（不知道可不填）

本项目campus-imaotai版本： X.X.X（请确保最新尝试是否还有问题）

## 问题描述

点击预约：出现
|ERROR  |IShopServiceImpl.java:170 |查询所在省市的投放产品和数量error: %s

1. 使用的什么功能
手动点击预约

3. 复现代码（如有）

```java
Console.log("报错了");
```

4. 测试涉及到的文件（如有）

**Comment by oddfar** [comment]
```java
String url = "https://static.moutai519.com.cn/mt-backend/xhr/front/mall/shop/list/slim/v3/" + getCurrentSessionId() + "/" + province + "/" + itemId + "/" + dayTime;
```

和 `sessionId` `省份` `itemId` `日期` 有关，自行检查拼接后的url，是否正确返回内容

**Comment by huangdongliang** [comment]
从新docker打包，把时区添加进去，后正常。
