### ISSUE TITLE
[bug]: 手动点击预约提示请求成功，但是日志报错

### ISSUE THREAD

**Issue by vow-vow** [oddfar/campus-imaotai#236]
## 版本情况

campus框架版本：1.0.11（不知道可不填）

本项目campus-imaotai版本： 1.0.11（请确保最新尝试是否还有问题）

## 问题描述

手动点击预约提示请求成功，但是日志报错

1. 使用的什么功能
手动预约

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

## 问题内容（如有）

日志内容：执行报错--[预约项目]：10942
[结果返回]：查询所在省市的投放产品和数量error: %s

## 补充说明（可选）
手动预约请求api:  ip:port/prod-api/imt/user/reservation?mobile=******
返回信息：{
    "msg": "请求访问：/imt/user/reservation，认证失败，无法访问系统资源",
    "code": 401
}

**Comment by oddfar** [comment]
没登录

**Comment by vow-vow** [comment]
应该登录了吧，token也重新刷新了，验证码也收到了

**Comment by huangdongliang** [comment]
你看一下容器里面的时间，建议重新打镜像，把timezone弄进去。 我刚开始也出现了  [结果返回]：查询所在省市的投放产品和数量error: %s

**Comment by wuchiawuchi** [comment]
> 你看一下容器里面的时间，建议重新打镜像，把timezone弄进去。 我刚开始也出现了 [结果返回]：查询所在省市的投放产品和数量error: %s

请问下 时区怎么弄呢

**Comment by huangdongliang** [comment]
RUN apt-get install  tzdata

WORKDIR /home/campus

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

**Comment by EwingYangs** [comment]
重启后端服务就可以了
