### ISSUE TITLE
V1.0.11怎么升级v1.0.12？

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [oddfar/campus-imaotai#239]
用打包的部署的？12没打包？

**Comment by caojjyy** [comment]
同问，

**Comment by xiankaiyao** [comment]
没有一键安装的zip包了？

**Comment by 272778299** [comment]
我的启动不了  大佬帮忙看下哪里出错啦
![1](https://github.com/oddfar/campus-imaotai/assets/49152744/62a0c86b-cac9-4089-8fff-fd4ed74b7129)
![2](https://github.com/oddfar/campus-imaotai/assets/49152744/053120e0-2406-4916-bb61-90931a709780)

**Comment by oddfar** [comment]
> 同问，我直接替换了jar包，可以显示是1.0.12但是我并不觉得这是正确的安装方式

这样就行

**Comment by oddfar** [comment]
> 没有一键安装的zip包了？

自行打包的，参考文档：https://oddfar.github.io/campus-doc/pages/8f2aa8/#%E6%89%93%E5%8C%85%E6%9C%80%E6%96%B0%E6%96%87%E4%BB%B6

**Comment by xiankaiyao** [comment]
https://github.com/xiankaiyao/campus-imaotai
按照教程打包好了，需要的自己下载吧
