### ISSUE TITLE
漏洞发现，部署完发现有个Redis unauthorized，未授权，连接后可以写ssh，请问大佬啥时候修一下这个漏洞

### ISSUE THREAD

**Issue by Lkdyyyy** [oddfar/campus-imaotai#24]
漏洞发现，部署完发现有个Redis unauthorized，未授权，连接后可以写ssh，请问大佬啥时候修一下这个漏洞
![image](https://github.com/oddfar/campus-imaotai/assets/48448041/c39ac599-4a3d-4511-abfe-cc419ef8b269)

**Comment by oddfar** [comment]
换新版本（V1.0.2），或防火墙关闭6379端口的外网访问
