### ISSUE TITLE
希望最新版加个全项目docker一键部署或者加个前端docker部署教程 

### ISSUE THREAD

**Issue by Peter-90** [oddfar/campus-imaotai#240]

**Comment by oddfar** [comment]
参考此文档：https://oddfar.github.io/campus-doc/pages/8f2aa8/#docker-compose%E5%90%AF%E5%8A%A8%E6%89%80%E6%9C%89%E6%9C%8D%E5%8A%A1
或者直接使用现成的 `V1.0.11`：https://github.com/oddfar/campus-imaotai/releases/download/V1.0.11/campus-imt-V1.0.11.zip

**Comment by huangdongliang** [comment]
我是全部自己打包成docker。redis， mysql也初始化进去，后端，前端。这样部署就方便的多。

**Comment by Peter-90** [comment]
> 参考此文档：https://oddfar.github.io/campus-doc/pages/8f2aa8/#docker-compose%E5%90%AF%E5%8A%A8%E6%89%80%E6%9C%89%E6%9C%8D%E5%8A%A1 或者直接使用现成的 `V1.0.11`：https://github.com/oddfar/campus-imaotai/releases/download/V1.0.11/campus-imt-V1.0.11.zip

感谢 我去研究一下

**Comment by xiankaiyao** [comment]
> 我是全部自己打包成docker。redis， mysql也初始化进去，后端，前端。这样部署就方便的多。

给个打包完的zip呗，不会自己打包

**Comment by huangdongliang** [comment]
[Uploading docker-compose.yml…]()  直接使用，我打好包了。

**Comment by xiankaiyao** [comment]
> Uploading docker-compose.yml… 直接使用，我打好包了。

下载不了啊

**Comment by huangdongliang** [comment]
不让上传，我没有办法，你自己写几个dockerfile ，项目里面也有，你上传到docker.io里面就可以了。修改一下docker-compose.yml就可以用了。

**Comment by xiankaiyao** [comment]
https://github.com/xiankaiyao/campus-imaotai
按照教程打包好了，需要的自己下载吧

**Comment by Peter-90** [comment]
> https://github.com/xiankaiyao/campus-imaotai 按照教程打包好了，需要的自己下载吧

大佬 那个redis和mysql的密码还有docker-compose里面的映射端口是不是都可以改

**Comment by xiankaiyao** [comment]
> > https://github.com/xiankaiyao/campus-imaotai 按照教程打包好了，需要的自己下载吧
> 
> 大佬 那个redis和mysql的密码还有docker-compose里面的映射端口是不是都可以改

可以，不过一键部署的密码不需要改
