### ISSUE TITLE
网页提示403

### ISSUE THREAD

**Issue by e014086** [oddfar/campus-imaotai#245]
网页提示403
![image](https://github.com/oddfar/campus-imaotai/assets/35452620/aa8c3d49-af13-4ee3-8f60-da8d3b8d4519)
![image](https://github.com/oddfar/campus-imaotai/assets/35452620/43399a57-5afb-4bdf-89d9-e25ff0817369)

## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： 1.0.11

## 问题描述
在群晖配置好了，打开网页的时候提示403 Forbidden nginx/1.25.3

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

**Comment by huangdongliang** [comment]
试一下 关闭selinux

**Comment by zhenglk** [comment]
selinux是关闭状态的还是报403

**Comment by huangdongliang** [comment]
看一下nginx启动的用户是谁，发布目录权限弄成一样的，或者nginx启动修改成nobody，最好看看日志
