### ISSUE TITLE
[bug]: 1.0.11版本使用docker直接安装的，所有功能都没问题，但是时间对不上，早了8小时

### ISSUE THREAD

**Issue by d0524** [oddfar/campus-imaotai#247]
## 版本情况

campus框架版本： 1.1.9

本项目campus-imaotai版本： 1.0.11

## 问题描述

1. V1.0.11版本使用docker直接安装的，所有功能都没问题，但是时间对不上，早了8小时，导致一直半夜预约，小白，不会更新12版本的包，请问该怎么解决
![image](https://github.com/oddfar/campus-imaotai/assets/75067680/f3a05030-7b33-4485-b828-60119a0ef551)

**Comment by will-bug** [comment]
同问, 同样使用docker.io的镜像部署的1.0.9的后端, 在本地部署的数据库, 新版的应该应该如何直接替换呢.

感谢开源~~

**Comment by oddfar** [comment]
> 同问, 同样使用docker.io的镜像部署的1.0.9的后端, 在本地部署的数据库, 新版的应该应该如何直接替换呢.
> 
> 感谢开源~~

删除旧的，重新部署
