### ISSUE TITLE
没有办法注册账号

### ISSUE THREAD

**Issue by DiShuai0817** [oddfar/campus-imaotai#254]
没有注册用户选项，参数设置里-账号自助-是否开启用户注册功能-已经设置true了

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/issues/158

**Comment by DiShuai0817** [comment]
感谢大佬，再问下，注册后的账号必须手动分配角色吗？刚测试注册后，登录没有imao的操作，需管理员分配。

**Comment by Bet5521** [comment]
campus-imaotai支持用户自助注册的，在访问地址后增加/register即可。
例如http://192.168.1.120:9999/register。注册成功以后需要admin去分配角色。
也可以用曲线救国的方式解决，比如做一个触发器，当用户新增时，自动分配角色。
