### ISSUE TITLE
[feature]: 希望增加 【邮箱】 推送消息方式

### ISSUE THREAD

**Issue by fancyfff** [oddfar/campus-imaotai#258]
## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本：1.0.12

## 问题描述

1. 使用的什么功能：推送消息功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

## 问题内容（如有）
pushplus 会有延迟，漏推问题

**Comment by oddfar** [comment]
有特殊需求请自行开发
