### ISSUE TITLE
对于一个非程序员来说这个部署实在是太复杂了

### ISSUE THREAD

**Issue by hanyuanda** [oddfar/campus-imaotai#266]
我按照视频都没搞定，有高手能指点一二不？

**Comment by huyewen7** [comment]
> 我按照视频都没搞定，有高手能指点一二不？

0基础，搭建成功 真不骗你，多看几遍视频 我花了2天时间 哈哈

**Comment by oddfar** [comment]
本项目用作技术学习交流为目的，故意提高使用门槛
