### ISSUE TITLE
[bug]: 登录验证码刷新不出，导致登录不了

### ISSUE THREAD

**Issue by vimcwal** [oddfar/campus-imaotai#269]
## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： 1.0.12（请确保最新尝试是否还有问题）

## 问题描述

1. 后端服务启动正常，使用的是镜像启动，外挂mysql和redis，但是前端页面无法刷出验证码，并且一直提示"登录状态已过期，您可以继续留在该页面，或者重新登录" ，导致登录不了web，这是漏设置什么了吗？

## 问题内容（如有）
![image](https://github.com/oddfar/campus-imaotai/assets/48074649/a6ada995-aef2-4a1c-a380-89ffaaf1be64)
![image](https://github.com/oddfar/campus-imaotai/assets/48074649/b22d7cd3-fc2b-4cfc-8a5d-a2460ff6cc13)

## 补充说明（可选）

{
    "msg": "请求访问：/prod-api/captchaImage，认证失败，无法访问系统资源",
    "code": 401
}

**Comment by oddfar** [comment]
清空下缓存，重新试试
