### ISSUE TITLE
[bug]: 在群晖的container里下载映像并打开容器后，出现了意外停止

### ISSUE THREAD

**Issue by gejinhuan** [oddfar/campus-imaotai#274]
无

无

无

## 版本情况

campus框架版本： X.X.X（不知道可不填）

本项目campus-imaotai版本： X.X.X（请确保最新尝试是否还有问题）
从群晖的container注册表里下载的最新版本
## 问题描述
<img width="328" alt="截屏2024-02-17 00 14 14" src="https://github.com/oddfar/campus-imaotai/assets/52098315/dab59dec-0f71-4fe0-9a95-6b8e2e665167">
容器启动后马上自动停止，重启启动，又自动停止，打开web，出现502的错误提示

1. 使用的什么功能

2. 复现代码（如有）

```java
Console.log("报错了");
```

3. 测试涉及到的文件（如有）

**Comment by oddfar** [comment]
没有日志，只有一个意外停止，分析不出来什么问题
**建议参考讨论区他人发布关于 群晖 的一些教程**

**Comment by sslzhou948** [comment]
[oddfar-campus-imaotai-1.csv](https://github.com/oddfar/campus-imaotai/files/14371615/oddfar-campus-imaotai-1.csv)
我遇到了yiya一样的问题，附件是日志

**Comment by sslzhou948** [comment]
补充下，我的群晖是DSM7.2.1
