### ISSUE TITLE
在campus 界面中<预约执行分钟>是什么意思呢？

### ISSUE THREAD

**Issue by ruixule** [oddfar/campus-imaotai#275]
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/3b9b70d3-e945-44e8-b919-43b57ea396d7)
我配置了4个账号，都是5分钟，但是只有一个账号成功了 。早上起来看程序好像把其他的给 修改了，

这个是什么意思呢

**Comment by eamon7** [comment]
同问，我的3个账号，每天其中都有1个账号没约上

**Comment by oddfar** [comment]
预约分钟代表的是：任务执行的分钟时间，比如为 `1`  代表`9点01分`执行；`5` 就是 `9点05分` 执行
会改掉，是因为勾选了`随机时间`，半夜就会把这人任务的时间随机修改了

**Comment by ruixule** [comment]
> 预约分钟代表的是：任务执行的分钟时间，比如为 `1`  代表`9点01分`执行；`5` 就是 `9点05分` 执行
> 会改掉，是因为勾选了`随机时间`，半夜就会把这人任务的时间随机修改了

如何关闭随机时间呢？按照配置来呢？

**Comment by oddfar** [comment]
> > 预约分钟代表的是：任务执行的分钟时间，比如为 `1`  代表`9点01分`执行；`5` 就是 `9点05分` 执行
> > 会改掉，是因为勾选了`随机时间`，半夜就会把这人任务的时间随机修改了
> 
> 如何关闭随机时间呢？按照配置来呢？

每个账号的修改界面里，关于 `随机预约` 开关
