### ISSUE TITLE
[bug]: 使用push plus 推送消息时，为什么只有创建 群组的人可以接受到消息，订阅群组的人接收不到消息呢？

### ISSUE THREAD

**Issue by ruixule** [oddfar/campus-imaotai#276]
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/350f0854-b92e-4455-a802-f9081a668bd4)
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/5873d795-5e21-4624-993a-ff5531ee0cdc)

如下图 订阅组的人接收不到消息，只有创建群组的人可以接收到消息

**Comment by ruixule** [comment]
针对这快的配置 是否有一个明确的说明 文档呢

**Comment by ruixule** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/d3808437-e094-4f09-b82f-6f055723c7e1)
询问客服后 才知道需要将 该参数带上 ，这个是在哪里配置的呢

**Comment by ruixule** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/4d018181-c662-439f-9033-6fd997599b55)
![image](https://github.com/oddfar/campus-imaotai/assets/33270841/2d66735f-e2ca-40e7-89c0-69c0bdf36e0d)
在这个方法这里 可以把topic 这个群组参数添加上么

**Comment by oddfar** [comment]
没有适配push plus群组推送，群聊推送也能看到别的账号，每个人需求不一样，特殊需求自己解决

**Comment by ruixule** [comment]
好的 谢谢
