### ISSUE TITLE
[Help] java后端部署启动报错

### ISSUE THREAD

**Issue by ChuuLim** [oddfar/campus-imaotai#278]
项目日志如下：
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.port' to java.lang.Integer:

    Property: server.port
    Value: 8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml
    Origin: "server.port" from property source "commandLineArgs"
    Reason: failed to convert java.lang.String to java.lang.Integer (caused by java.lang.NumberFormatException: For input string: "8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml")

Action:

Update your application's configuration

[0;39m
![图片](https://github.com/oddfar/campus-imaotai/assets/25174496/72762342-abc7-40d8-8ffd-7909446cd8f9)

求助，该如何解决

**Comment by oddfar** [comment]
`8160--Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml` 不对，后边有空格的
正确的： `8160 --Dspring.config.location=/www/wwwroot/campus-imaotai/application-prod.yml`

**Comment by ChuuLim** [comment]
感谢大佬，确实少了个空格，现在可以运行了
