### ISSUE TITLE
[bug]: doc目录中的docker-compose 的campus docker镜像404

### ISSUE THREAD

**Issue by LuisRain** [oddfar/campus-imaotai#279]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.0.12

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Windows (64)

### 运行架构

None

### 问题描述

[bug]: doc目录中的docker-compose 的campus docker镜像404

### 期望的结果是什么？

正常有镜像

**Comment by LuisRain** [comment]
我要疯掉了这个项目，sql中的admin用户登录密码都得自己猜，不然就得看源码重新生成加密的用户

**Comment by oddfar** [comment]
填写 issues 的时候，有一些注意事项都告诉你了如何是解决本项目的问题

### 第一：查看[文档](https://oddfar.github.io/campus-doc/campus-imaotai)里是否有解决方案

<img width="974" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/cc6b9c69-e255-4636-af18-10da2878ce34">

下面是文档的内容：
<img width="1281" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/5e81c825-6bf3-428b-8200-5c194c0b8bbe">
系统默认有的账号信息都有标示：
<img width="703" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/d0dda9ea-f141-4616-aed3-5e7eb8178bc0">

### 第二：我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。

在 issue 中搜索关键词 “密码”，可以看到
<img width="623" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/e3ed63c9-29cc-4251-a709-e7ed82efaeaf">
这里面也有你想要的答案：
<img width="580" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/c67f0422-b63a-46ab-b2a3-df36ed4c5454">
