### ISSUE TITLE
真是重新定义了一键部署。。。。。

### ISSUE THREAD

**Issue by xjblszyy** [oddfar/campus-imaotai#287]
都用docker了，还这么麻烦。。。。

**Comment by oddfar** [comment]
故意的，提高门槛

**Comment by EasyIsAllYouNeed** [comment]
哈哈哈

**Comment by TyCoding** [comment]
也是服了，瞎写

**Comment by Pandolar** [comment]
确实很折腾  对小白

> > 也是服了，瞎写
> 
> 怎么瞎写了

上手的门槛还是挺高的，java本来就比较复杂，教程还写的乱七八糟，劝退了不少人，所以为什么不打包好后docker-compose一键部署呢？

**Comment by oddfar** [comment]
> 确实很折腾 对小白
> 
> > > 也是服了，瞎写
> > 
> > 
> > 怎么瞎写了
> 
> 上手的门槛还是挺高的，java本来就比较复杂，教程还写的乱七八糟，劝退了不少人，所以为什么不打包好后docker-compose一键部署呢？

有没有一种可能，本来就有打包好的docker-compose.zip

**Comment by Pandolar** [comment]
有没有一种可能，你说的打包好的docker-compose.zip链接失效很久了
https://oddfar.github.io/campus-doc/pages/8f2aa8/#docker-compose%E5%90%AF%E5%8A%A8%E6%89%80%E6%9C%89%E6%9C%8D%E5%8A%A1

https://github.com/oddfar/campus-imaotai/doc/docker-compose.zip

**Comment by oddfar** [comment]
> 有没有一种可能，你说的打包好的docker-compose.zip链接失效很久了 https://oddfar.github.io/campus-doc/pages/8f2aa8/#docker-compose%E5%90%AF%E5%8A%A8%E6%89%80%E6%9C%89%E6%9C%8D%E5%8A%A1
> 
> https://github.com/oddfar/campus-imaotai/doc/docker-compose.zip

还有没有一种可能，你可以链接地址猜一下在项目的哪个位置？

<img width="800" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/76616434/1cf06a0d-4b6c-4b4a-93b4-45f4993fc4d8">

**Comment by Pandolar** [comment]
没看过你写的代码，也许是个真java大佬，但是写的教程很乱是毋庸置疑的

如果你想给小白用，就用心去写教程，或者把文档开放出来让社区其他的人来搞；

**Comment by Pandolar** [comment]
> Reference in new issu

是的，我看到了，所以我说你的链接失效了，文档也不更新，小白还得自己去翻仓库。

**Comment by oddfar** [comment]
> 没看过你写的代码，也许是个真java大佬，但是写的教程很乱是毋庸置疑的
> 
> 如果你想给小白用，就用心去写教程，或者把文档开放出来让社区其他的人来搞；

做开源项目本身就是耗费精力，文档有问题没更新是因为无暇照顾
由于本项目的敏感性，故意这样设计提高使用门槛的，并不想满足“小白”用户
**有一些用户会利用本项目进行不好的操作**

**Comment by oddfar** [comment]
文档仓库一直处于公开状态：https://github.com/oddfar/campus-doc
感兴趣的可以去维护下

**Comment by Pandolar** [comment]
> > 没看过你写的代码，也许是个真java大佬，但是写的教程很乱是毋庸置疑的
> > 如果你想给小白用，就用心去写教程，或者把文档开放出来让社区其他的人来搞；
> 
> 做开源项目本身就是耗费精力，文档有问题没更新是因为无暇照顾 由于本项目的敏感性，故意这样设计提高使用门槛的，并不想满足“小白”用户 **有一些用户会利用本项目进行不好的操作**

如果是处于该目的才写的比较复杂的话，也情有可原，不管怎么说，还是感谢大佬的开源

**Comment by sdjdd** [comment]
> 故意这样设计提高使用门槛的

🤣
