### ISSUE TITLE
有时间做个葫芦娃 7 个平台的预约吗

### ISSUE THREAD

**Issue by hcliu987** [oddfar/campus-imaotai#29]

**Comment by hcliu987** [comment]
加密算法写好了，但是爬虫不会

**Comment by oddfar** [comment]
我不会😭

**Comment by hcliu987** [comment]
我基本上都写好了，就是整合没有空
有时间做吗

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 致远 ***@***.***>
发送时间: Wednesday, July 26, 2023 6:11:29 PM
收件人: oddfar/campus-imaotai ***@***.***>
抄送: hcliu987 ***@***.***>; Author ***@***.***>
主题: Re: [oddfar/campus-imaotai] 有时间做个葫芦娃 7 个平台的预约吗 (Issue #29)


我不会😭

**Comment by oddfar** [comment]
可以看一下尝试做做，🛰️联系我

**Comment by hcliu987** [comment]
发下微信

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 致远 ***@***.***>
发送时间: Wednesday, July 26, 2023 10:36:58 PM
收件人: oddfar/campus-imaotai ***@***.***>
抄送: hcliu987 ***@***.***>; Author ***@***.***>
主题: Re: [oddfar/campus-imaotai] 有时间做个葫芦娃 7 个平台的预约吗 (Issue #29)


可以看一下尝试做做，🛰️联系我

**Comment by oddfar** [comment]
zhiyuan799

**Comment by TSYMQMYST** [comment]
能也发我一份吗?  我也想集成到自己的系统里去
