### ISSUE TITLE
[bug]: ### Error updating database. Cause: java.sql.SQLException: Field 'role_id' doesn't have a default value 

### ISSUE THREAD

**Issue by King0420** [oddfar/campus-imaotai#291]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.1.9

### 本项目 campus-imaotai 版本

1.0.11

### 运行环境

CentOS

### 运行架构

None

### 问题描述

使用的是docker 一键部署，无法给新创建用户i茅台权限
![image](https://github.com/oddfar/campus-imaotai/assets/104044278/4587cdc5-98db-4b74-98bb-701dc938ad44)

### 期望的结果是什么？

可以修改

**Comment by k8scat** [comment]
+1

**Comment by k8scat** [comment]
<img width="524" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/55872984/6eb8bae9-087c-41ea-97ef-009db1d2d584">

**Comment by k8scat** [comment]
> <img alt="image" width="524" src="https://private-user-images.githubusercontent.com/55872984/306455533-6eb8bae9-087c-41ea-97ef-009db1d2d584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzY1NjEsIm5iZiI6MTcwODQ3NjI2MSwicGF0aCI6Ii81NTg3Mjk4NC8zMDY0NTU1MzMtNmViOGJhZTktMDg3Yy00MWVhLTk3ZWYtMDA5ZGIxZDJkNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAwNDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOTg4ZWEzZTgxMTYyYWU5YzNhYzJlZTk2NTkwOTUwOWEwZmRiNWRhOThlODIyMzViY2E2MWQzMTAyNWZlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w6gy_ui3ADedFx8GrWIH1FwcQ6tWBOAHNrnQDvDiKek">

检查 sys_user_role 表没有对应 sys_user 的记录，但查询出来的 sysUser 却包含一个角色的空数据

<img width="891" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/55872984/25598f91-18e2-49b9-af56-eaaab7a7d037">

**Comment by k8scat** [comment]
看样子是mapping的配置有问题，导致填充了一个空的role

<img width="1225" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/55872984/1aa7169d-a800-4300-8b11-3061db79eb74">

**Comment by k8scat** [comment]
快速修复：#298
