### ISSUE TITLE
[bug]: phpmyadmin 执行 sql 创建数据库报错

### ISSUE THREAD

**Issue by clz1024** [oddfar/campus-imaotai#296]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

CentOS

### 运行架构

x86

### 问题描述

宝塔面板 phpmyadmin 执行相应 sql 文件创建数据库报错
SQL 查询：
-- ----------------------------
-- Table structure for i_item
-- ----------------------------
DROP TABLE IF EXISTS `i_item`;
MySQL 返回： 文档

#1046 - No database selected

### 期望的结果是什么？

成功创建数据库

**Comment by wzcsimon123** [comment]
没选择数据库怎么实行sql呢
