### ISSUE TITLE
更改nginx接口后，提示404错误

### ISSUE THREAD

**Issue by Wolfie-glitch** [oddfar/campus-imaotai#3]
![image](https://github.com/oddfar/campus-imaotai/assets/60575769/cde7582d-3b87-4922-ab22-ed43f3517228)

更改了nginx的接口后成这样了，显示不出验证码

**Comment by wangkangfeng1999** [comment]
我也这样

**Comment by oddfar** [comment]
改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“

**Comment by Wolfie-glitch** [comment]
> 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“

在yml文件里，我就是这么改的，改出来就是图片上那样。

**Comment by Wolfie-glitch** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/60575769/19ca6702-60f8-4dee-8a3c-34b022e6aa28)
奇怪的是，部署后我的容器也只有2个，少了server和redis

**Comment by wangkangfeng1999** [comment]
> 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“

我没有改端口，部署出来就是这样的

**Comment by wangkangfeng1999** [comment]
> > 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“
> 
> 我没有改端口，部署出来就是这样的

![Uploading image.png…]()

**Comment by wangkangfeng1999** [comment]
> > > 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“
> > 
> > 
> > 我没有改端口，部署出来就是这样的
> > ![image](https://user-images.githubusercontent.com/68324194/251968445-231a36a8-27ed-45f7-b3c4-b2041a4b1f1f.png)

### 重新启动了一下 问题解决了

>

**Comment by Wolfie-glitch** [comment]
> > > > 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“
> > > 
> > > 
> > > 我没有改端口，部署出来就是这样的
> > > ![image](https://user-images.githubusercontent.com/68324194/251968445-231a36a8-27ed-45f7-b3c4-b2041a4b1f1f.png)
> 
> ### 重新启动了一下 问题解决了
> >

![image](https://github.com/oddfar/campus-imaotai/assets/60575769/64c49f11-7492-47c4-8a7f-d458d8e03cb9)


重启了，redis还是没有

**Comment by wangkangfeng1999** [comment]
> > > > > 改端口的时候，把“80:80”改成 “81:80”，后边的80不可更改，“新未被占用的端口:80“
> > > > 
> > > > 
> > > > 我没有改端口，部署出来就是这样的
> > > > ![image](https://user-images.githubusercontent.com/68324194/251968445-231a36a8-27ed-45f7-b3c4-b2041a4b1f1f.png)
> > 
> > ### 重新启动了一下 问题解决了
> > >
> 
> ![image](https://github.com/oddfar/campus-imaotai/assets/60575769/64c49f11-7492-47c4-8a7f-d458d8e03cb9)
> 
> 
> 重启了，redis还是没有

咱俩问题不一样，我那几个服务是不缺的，你要不再重新build一下

**Comment by oddfar** [comment]
> > > > > 改端口的时候，把“80:80”改成“81:80”，后边的80不可更改，“新随身占用的端口:80”
> > > > 
> > > > 
> > > > 我没有改端口，配置出来就是这样的
> > > > ![图像](https://user-images.githubusercontent.com/68324194/251968445-231a36a8-27ed-45f7-b3c4-b2041a4b1f1f.png)
> > 
> > 
> > ### 重新启动一下问题解决了
> > >
> 
> ![图像](https://user-images.githubusercontent.com/60575769/251969633-64c49f11-7492-47c4-8a7f-d458d8e03cb9.png)
> 
> 重启了，redis还是没有

看看报错内容是啥，`docker logs 容器id` ，若之前构建错误，就删掉镜像和容器，重新构建和启动试试

**Comment by Wolfie-glitch** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/60575769/e81c41ce-fd83-4c7f-a3a8-35d259ebeecc)

不懂，在本地运行了又报这样的错，纯小白表示不懂，您给瞅瞅

**Comment by oddfar** [comment]
看报错内容是创建失败，可能没权限，试试用root账户，还不行的话那就等客户端版吧，有大佬准备改个

**Comment by Wolfie-glitch** [comment]
好的，谢谢您
