### ISSUE TITLE
请教关于破解问题

### ISSUE THREAD

**Issue by 419860198** [oddfar/campus-imaotai#304]
不懂软件破解 问下大佬些像接口中md5 salt和 AES的秘钥这些是如何破解的

**Comment by Eeeextend** [comment]
想知道可以了解移动逆向相关的知识。以安卓平台为例
接口加密参数来自本地代码，通常在安卓的so文件中。
你需要追踪这个加密参数的生成代码，找出关键的salt。
具体的需要涉及到很多知识点，包括密码学加固脱壳代码hook trace 。

**Comment by 419860198** [comment]
了解3q
