### ISSUE TITLE
[bug]: 启动时报错，不能访问i茅台的接口导致

### ISSUE THREAD

**Issue by kaig2008** [oddfar/campus-imaotai#307]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.0.12

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Windows (64)

### 运行架构

x86

### 问题描述

![image](https://github.com/oddfar/campus-imaotai/assets/2736273/9d33c718-2d17-4b3b-9c54-22e633bb7721)
启动报错：
GET https://static.moutai519.com.cn/mt-backend/xhr/front/mall/index/session/get/1708531200000
报java.net.SocketException: Connection reset

### 期望的结果是什么？

如何处理这个问题

**Comment by regrlomon** [comment]
感觉是你网络的原因，换个wifi试试看
