### ISSUE TITLE
[Feature] 指定预约店，不根据ip地址变化

### ISSUE THREAD

**Issue by viazry** [oddfar/campus-imaotai#308]
## 例行检查

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## 功能请求
能加个功能，指定门店的ID后，预约类型为固定，无论变化申请地址，门店不会变更

## 解决方案和应用场景
在两个城市间跑，地址随时变，想指定到一个店

**Comment by regrlomon** [comment]
你可以指定相同的“门店商品ID“，然后预约申请的所在城市其实就是“门店商品ID“所在的城市
