### ISSUE TITLE
[bug]：新用户注册不能自动加入"i茅台"角色信息，应该怎么设置？

### ISSUE THREAD

**Issue by Solucky0** [oddfar/campus-imaotai#311]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.1.9

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

CentOS

### 运行架构

x86

### 问题描述

新用户注册不能自动加入"i茅台"角色信息，应该怎么设置？

### 期望的结果是什么？

处理方法

**Comment by Eternallyl** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/59507559/555d7419-4a16-41e4-8297-e8e33438cdfa)

这么加来应急
