### ISSUE TITLE
如果类型填了“预约本市出货量最大的门店”，那么为啥还要填”门店商品id“?

### ISSUE THREAD

**Issue by wangxiaotian23** [oddfar/campus-imaotai#313]
## 例行检查

疑问：我看“门店商品id“是必填项，但是选了”预约本市出货量最大的门店“，这个能会动态查找哪个是出货量最大的门店吗

**Comment by wangxiaotian23** [comment]
刚翻了下代码，发现“门店商品id“好像也没有用上，而是会根据shopType是1还是2找出shopId。那有点没搞懂“门店商品id“设置成必填项有啥原因吗？

**Comment by regrlomon** [comment]
门店商品id是为了获取你预约的城市等各种信息的

**Comment by snow-tyan** [comment]
也就是说通过商品ID定位省市，再根据shopType来选择出货量最大还是最近？不能指定商品ID吗😂

**Comment by regrlomon** [comment]
> 也就是说通过商品ID定位省市，再根据shopType来选择出货量最大还是最近？不能指定商品ID吗😂

是的，商品id只能说明你要预购哪些，没法定位到你的城市

**Comment by oddfar** [comment]
这个是因为，申购接口需要经纬度位置，根据这个就可以定位门店远近
最开始是通过手动填写 `经纬度` ，然后因为大部分人说太麻烦
后边就根据 `门店id` 信息，获取到了经纬度、省、市等信息
主要为了约束填写错的配置信息
