### ISSUE TITLE
登陆密码忘了怎么办？

### ISSUE THREAD

**Issue by justincnn** [oddfar/campus-imaotai#316]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### 本项目 campus-imaotai 版本

1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 问题描述

请问登陆密码给忘记了，如何处理

### 期望的结果是什么？

谢谢

**Comment by Bet5521** [comment]
用数据库工具链接数据库，然后在用户表里修改一下密码。不确定加密方式可以找一个知道密码的行修改到你记不住的行
