### ISSUE TITLE
部分人素质堪忧。此issue希望作者进行删除

### ISSUE THREAD

**Issue by Winspain** [oddfar/campus-imaotai#320]
## 例行检查

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**Comment by LeiDuang** [comment]
你真是闲的蛋疼，不中的消息天天提示，真有问题了人会麻木的以为还是申购不中，我fork作者的项目还取消了一部分推送，你倒好再加上一堆

**Comment by Winspain** [comment]
> 你真是闲的蛋疼，不中的消息天天提示，真有问题了人会麻木的以为还是申购不中，我fork作者的项目还取消了一部分推送，你倒好再加上一堆

有事说事，你妈教你这么做人的？嘴巴不干净要不要你爹我教一下你怎么说话？莫名其妙…傻逼，闲的jb疼就剁了

**Comment by LeiDuang** [comment]
那我再说一遍，闲的蛋疼

**Comment by huluohu** [comment]
我也说一遍，你是闲的蛋疼。。。还不让人说的那种。

另外，不回提issue，请别学人家也来玩github。

**Comment by Winspain** [comment]
> 我也说一遍，你是闲的蛋疼。。。还不让人说的那种。
> 
> 另外，不回提issue，请别学人家也来玩github。

我也说一遍，你是闲的蛋疼。。。申购不中的提示，方便我每天检验是否有在正常申购，获取申购结果。你只加自己的手机号，当然可以登录i茅台去看。别的呢？一个个去app查看？
另外，不会打字，就别做人来打字了。不会还是不“回”？

**Comment by huluohu** [comment]
我在说一遍，你也就“会”抠字眼的本事了，我写回你不是也知道是会吗？你愿意扣，你可以把github上的笔误都抠个遍啊，德行！
另外，不会用就别跑出来丢人现眼了，好好在被窝里抠字眼，练个“抠字眼专业户8级”不香吗！

**Comment by Winspain** [comment]
> 我在说一遍，你也就“会”抠字眼的本事了，我写回你不是也知道是会吗？你愿意扣，你可以把github上的笔误都抠个遍啊，德行！ 另外，不会用就别跑出来丢人现眼了，好好在被窝里抠字眼，练个“抠字眼专业户8级”不香吗！

什么jb德行！你妈教你上网这么说话的？这是你家随便喷粪丢人现眼的？傻逼玩意，回家玩屎去吧。没有脑子就拿坨屎顶上。
你爹已经说了使用场景，还bb，老b登回家玩你吊毛去吧？

**Comment by huluohu** [comment]
666，你的场景就是满嘴喷粪，我敕封你一个“喷粪专业户”头衔，赐你世袭罔替，谢恩什么的就免了吧。

**Comment by Winspain** [comment]
> 666，你的场景就是满嘴喷粪，我敕封你一个“喷粪专业户”头衔，赐你世袭罔替，谢恩什么的就免了吧。

傻逼儿子，快回家给你老母上坟去吧。记得顶一坨屎

**Comment by huluohu** [comment]
再给你加封“哭丧专业户”，同样世袭罔替，不用谢恩。

**Comment by Winspain** [comment]
> 再给你加封“哭丧专业户”，同样世袭罔替，不用谢恩。

乖儿，你给自己老母哭就行了。爹允了，传下去让你子子孙孙都给你老母哭起来
