### ISSUE TITLE
[Feature] 是否可以加入telegram的推送？

### ISSUE THREAD

**Issue by justincnn** [oddfar/campus-imaotai#321]
## 例行检查

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## 功能请求
微信公众号推送的效率太慢，且内容呈现不友好，
望作者采纳，谢谢

**Comment by smy0419** [comment]
这个功能有个鸡毛用。

**Comment by oddfar** [comment]
不支持，有特殊需求请自行实现
