### ISSUE TITLE
日志显示申购完成

### ISSUE THREAD

**Issue by syliang2020** [oddfar/campus-imaotai#324]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

CentOS

### 运行架构

x86

### 问题描述

日志显示预约成功，但是登录i茅台app看不到预约记录，退出重新登录页看不到

### 期望的结果是什么？

-

**Comment by SnowingFox** [comment]
在哪看申购完成？

**Comment by syliang2020** [comment]
> 在哪看申购完成？

日志啊，现在app也可以看到历史申购记录了
