### ISSUE TITLE
[bug]: 8号之后的接口失效问题 UnknownHostException:apps.apple.com 后端jar包为1.0.12

### ISSUE THREAD

**Issue by AaronYang233** [oddfar/campus-imaotai#326]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Ubuntu

### 运行架构

None

### 问题描述

验证码失效

### 期望的结果是什么？

正常

**Comment by oddfar** [comment]
这个接口是获取app的最新版本号
