### ISSUE TITLE
报告一个预约的Bug

### ISSUE THREAD

**Issue by LinkStark** [oddfar/campus-imaotai#33]
填写了Pushplus的推送token之后，在预约两家商品时，例如：10213@10214，会出现第二件商品预约失败的问题，暂不清楚预约更多商品会怎么样，环境为win10，账号有两个，出问题的是顺序为第二的账号（第一个账号未填写），清空pushplus token之后一切正常

**Comment by oddfar** [comment]
用的什么版本，查看下容器日志，`docker logs campus-server`
