### ISSUE TITLE
[bug]: windows部署可以linux 部署就是不行

### ISSUE THREAD

**Issue by xianglongwei** [oddfar/campus-imaotai#332]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Ubuntu

### 运行架构

x86

### 问题描述

部署的时候报错ampus-imt-V1.0.11# Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: campus-redis/172.18.0.2:6378
看报错貌似是redis 连接问题，但是这个6378并没有看到有映射默认的不是6379吗？
有没有大佬遇到过这样的问题。我windows docker根据配置文件部署成功了，但是在linux上弄死不行。配置都是一模一样的。防火墙也是关闭了的。
![image](https://github.com/oddfar/campus-imaotai/assets/52027227/1a0ab78f-22b7-48db-ba51-8c9a12fb4c00)
![image](https://github.com/oddfar/campus-imaotai/assets/52027227/ac7b71a9-f598-4f6e-a72f-37136efe7957)

### 期望的结果是什么？

能部署成功

**Comment by xianglongwei** [comment]
有没有大佬遇到过相同问题？

**Comment by czmchen** [comment]
部署成功后，登陆进去，能访问这些功能么？

**Comment by k8scat** [comment]
参考 #203
