### ISSUE TITLE
404接口错误搭建好了后

### ISSUE THREAD

**Issue by Clove-MJC** [oddfar/campus-imaotai#334]
![image](https://github.com/oddfar/campus-imaotai/assets/29298720/c81d3029-d134-44f2-9569-5e7cb6966b73)

**Comment by kratosmy** [comment]
同，/prod-api/captchaImage 404

**Comment by fbotp** [comment]
同

**Comment by LeiDuang** [comment]
后端页面是否显示正常，如果后端正常就是前端配置后端路径错误，前端访问不了后端

**Comment by k8scat** [comment]
参考 #203

**Comment by big-kota** [comment]
参考这个方案
https://github.com/oddfar/campus-imaotai/issues/118#issuecomment-2024395895
