### ISSUE TITLE
[Feature] 建议加入多门店指定

### ISSUE THREAD

**Issue by lxtxqr** [oddfar/campus-imaotai#335]
在我所在的城市
同时预约多款酒的情况下，会出现同一个门店酒备货不足的情况，就会出现预约不了的情况。
希望加入 多门店预约，作为备选 如果预约不成功 可以使用备选自动预约

**Comment by oddfar** [comment]
门店当日没有的情况下，会根据填写的配置约其他门店，可以看下此issues：https://github.com/oddfar/campus-imaotai/issues/313
