### ISSUE TITLE
[bug]: InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by Bruce-Jiang** [oddfar/campus-imaotai#339]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.1.9

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Windows (64)

### 运行架构

x86

### 问题描述

执行报错--[预约项目]：10941 [结果返回]：InvalidKeyException: Illegal key size

### 期望的结果是什么？

希望不报错，程序有正确的输出

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/issues/69
