### ISSUE TITLE
新注册的用户 进去没有茅台项目

### ISSUE THREAD

**Issue by 546220777** [oddfar/campus-imaotai#34]
后台给了普通用户  茅台权限的  新注册普通用户进去后台就一个首页    看不到茅台项目   而且后台手动添加的用户 去登录 会提示用户不存在

**Comment by oddfar** [comment]
本项目目前适合自用，不建议使用其他用户添加i茅台用户，并未开启此功能

**Comment by Bet5521** [comment]
想要商用可以给@oddfar提供一定费用进行定制，或者自己基于此开源项目做进一步的开发，将你想要的用户注册功能和其他例如用户用户密码自助找回等其他功能。
或者说你用曲线救国的方式解决新增用户授权I茅台角色的功能。

**Comment by oddfar** [comment]
> 想要商用可以给@oddfar提供一定费用进行定制，或者自己基于此开源项目做进一步的开发，将你想要的用户注册功能和其他例如用户用户密码自助找回等其他功能。 或者说你用曲线救国的方式解决新增用户授权I茅台角色的功能。

本项目不鼓励不支持商用，像一些奇怪的操作（注册账号无角色权限等），都是故意设计的，提高本项目的门槛
