### ISSUE TITLE
需要有一个申购成功的消息提醒

### ISSUE THREAD

**Issue by a3312223** [oddfar/campus-imaotai#345]
## 例行检查

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## 功能请求
我把我们公司的所有人都加上去了，结果申购了几天，发现一只没有中，是不是18点申购成功的不会提醒。

## 解决方案和应用场景
我想有一个18点申购成功的提醒，并且提示是那个账号中奖了，麻烦作者大大了，。

**Comment by Dunky-Z** [comment]
1. 中签茅台官方会发短信提醒。
2. 多个账号同一个IP频繁申购，你不怕黑号吗？虽然没有明确的规定说同个IP频繁申购会判定黑号，但是你这样的操作是不太合常理的。
3. 申购成功本身就是概率事件，需要运气。约一年都没中过的大有人在

**Comment by huluohu** [comment]
1、你是多大面子申购了几天就得中？
2、本身就支持设置pushplus微信通知
3、如楼上所说，多个账号同一个IP频繁申购更难中，还把全公司所以人都加上，显得你了。。。

**Comment by a3312223** [comment]
支持设置pushplus微信通知，怎么设置

**Comment by xubillde** [comment]
全公司团灭啊

**Comment by a3312223** [comment]
> 1. 中签茅台官方会发短信提醒。
> 2. 多个账号同一个IP频繁申购，你不怕黑号吗？虽然没有明确的规定说同个IP频繁申购会判定黑号，但是你这样的操作是不太合常理的。
> 3. 申购成功本身就是概率事件，需要运气。约一年都没中过的大有人在
