### ISSUE TITLE
[Feature] 葫芦娃的这个功能什么时候上了？

### ISSUE THREAD

**Issue by ruixule** [oddfar/campus-imaotai#351]
## 解决方案和应用场景

![image](https://github.com/oddfar/campus-imaotai/assets/33270841/76b3a3de-06c6-4ddf-af57-f895a4672b62)
我在这个仓库看到，这个图片相信不是PS的，葫芦娃的这个功能什么时候上了？

https://github.com/yize8888/maotai/issues/51

**Comment by 1107046315** [comment]
公众号某位大佬分享了部署包 善于搜索就能找到

**Comment by ruixule** [comment]
> 公众号某位大佬分享了部署包 善于搜索就能找到

大佬，可以分享下公众号吗？谢谢

**Comment by hsi-chan** [comment]
> 公众号某位大佬分享了升级包 善于搜索就能找到

给个关键字吧，谢谢大佬

**Comment by 1107046315** [comment]
> 给个关键字吧，谢谢大佬

零和一的那些事

**Comment by newbiene** [comment]
葫芦娃的token是多久失效的

**Comment by 1107046315** [comment]
貌似一周左右

**Comment by njuws** [comment]
> > 公众号某位大佬分享了升级包 善于搜索就能找到
> 
> 给个关键字吧，谢谢大佬

微信公众号搜索“成都小默”，点击“进入群聊-部署包”。
但token还是手动获取的，还是麻烦。
