### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by qiulifei992** [oddfar/campus-imaotai#355]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.19

### 本项目 campus-imaotai 版本

1.0.12

### 运行环境

Ubuntu

### 运行架构

ARM [32] (别名：AArch32 / ARMv7）

### 问题描述

安装报错：
 => ERROR [campus-server internal] load metadata for docker.io/adoptopen  69.0s
------
 > [campus-server internal] load metadata for docker.io/adoptopenjdk/openjdk8:latest:
------
failed to solve: adoptopenjdk/openjdk8: failed to resolve source metadata for docker.io/adoptopenjdk/openjdk8:latest: no match for platform in manifest: not found

### 期望的结果是什么？

恳请能修复一下，谢谢

**Comment by oddfar** [comment]
换个jdk试试
