### ISSUE TITLE
[bug]: 首页版本号显示疑似错误

### ISSUE THREAD

**Issue by YusCoding** [oddfar/campus-imaotai#364]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

未知

### 本项目 campus-imaotai 版本

campus-imaotai:1.0.13

### 运行环境

CentOS

### 运行架构

x86

### 问题描述

如题，使用docker部署的后端项目，前端直接挂在服务器的nginx，已稳定正常运行超过三个月，今天更新了项目，具体操作为：docker pull新的镜像并重启运行，下载了新的前端包并上传解压。但是打开首页仍旧展示版本号为campus-imaotai:1.0.11。不知道是否我部署操作出现错误还是项目版本号展示是写死的。。。

### 期望的结果是什么？

期望更新版本后能够正确显示项目版本号

### 补充说明（可选）

经过我的确认，似乎是docker镜像未做更新？镜像更新时间是五个月以前？

**Comment by oddfar** [comment]
docker hub那边镜像没更新，没配置这边的自动打包镜像
最新的镜像请看：https://github.com/oddfar?tab=packages&repo_name=campus-imaotai

**Comment by YusCoding** [comment]
好的！一个小问题：这里的镜像和官方库都是一样的运行参数的哦？因为有点担心拿这个替换掉官方镜像库那个版本之后跑不起来😂

**Comment by YusCoding** [comment]
> docker hub那边镜像没更新，没配置这边的自动打包镜像 最新的镜像请看：https://github.com/oddfar?tab=packages&repo_name=campus-imaotai

好的！一个小问题：这里的镜像和官方库都是一样的运行参数的哦？因为有点担心拿这个替换掉官方镜像库那个版本之后跑不起来😂

**Comment by oddfar** [comment]
> > docker hub那边镜像没更新，没配置这边的自动打包镜像 最新的镜像请看：https://github.com/oddfar?tab=packages&repo_name=campus-imaotai
> 
> 好的！一个小问题：这里的镜像和官方库都是一样的运行参数的哦？因为有点担心拿这个替换掉官方镜像库那个版本之后跑不起来😂

忘记了，不太确定哦，以最新文档为准
