### ISSUE TITLE
提点功能开发意见

### ISSUE THREAD

**Issue by xiongchao902** [oddfar/campus-imaotai#369]
## 例行检查

+ [ ] 门店这边是否可以做个轮询，防止门店没货造成漏约
+ [ ] 周末购能否进行自动约
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

## 解决方案和应用场景
+ [ ] 门店这边是否可以做个轮询，防止门店没货造成漏约
+ [ ] 周末购能否进行自动约

**Comment by oddfar** [comment]
门店目前这边就是没货不约，有2种预约方式：距离最近，出货量最大，都是从有货的里面选择

**Comment by xiongchao902** [comment]
这边计划开发周末快乐购吗？
我通过抓包抓到的数据发现很平时一样，但是改造的时候失败了
