### ISSUE TITLE
docker构建Java报错

### ISSUE THREAD

**Issue by yxd-python** [oddfar/campus-imaotai#37]
会提示anifest for java:8 not found: manifest unknown: manifest unknown
将dockerfile里的Java：8改为openjdk:8就可以了

**Comment by yating1022** [comment]
有用，感谢

**Comment by q-sue** [comment]
=> ERROR [campus-server internal] load metadata for docker.io/library/openjdk:8                                                                                                                                                                              0.1s
------
 > [campus-server internal] load metadata for docker.io/library/openjdk:8:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 8]: 403 Forbidden
这是什么情况

**Comment by chouxiang99** [comment]
有用，感谢

> 会提示anifest for java:8 not found: manifest unknown: manifest unknown 将dockerfile里的Java：8改为openjdk:8就可以了
