### ISSUE TITLE
请问在NAS的docker中应该如何部署？

### ISSUE THREAD

**Issue by Roger1219** [oddfar/campus-imaotai#371]
你好，开发者。我用的是极空间的NAS，内置docker，可以pull项目需要的4个dokcer镜像，但是无法像windows中那样使用命令行运行docker-compose build以及  docker-compose up -d来部署容器，只能从单个镜像创建，请问这种情况应该怎么办？
PS：NAS上面无法运行命令行，只能从窗口界面导入镜像或者从DockerHub上面下载。

**Comment by oddfar** [comment]
参考下issues和discussions，我记得有类似的情况
