### ISSUE TITLE
[bug]: 群晖7.2使用docker-compose部署，卡在最后一步

### ISSUE THREAD

**Issue by nageshuizeii** [oddfar/campus-imaotai#378]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已确认我已升级到最新版本（最新代码）测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/oddfar/campus-imaotai/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### campus框架版本

1.0.13

### 本项目 campus-imaotai 版本

1.0.13

### 运行环境

其它（请在下方说明）

### 运行架构

x86

### 问题描述

ash-4.4# docker-compose build
[+] Building 0.0s (0/0)                                                         
[+] Building 0.4s (1/2)                                                         
 => [internal] load build definition from mysql-dockerfile                 0.3s 
 => => transferring dockerfile: 170B                                       0.0s
[+] Building 0.6s (2/3)                                                         
[+] Building 0.7s (2/3)                                                         
[+] Building 2.2s (3/3) FINISHED                                                
 => [internal] load build definition from mysql-dockerfile                 0.3s
 => => transferring dockerfile: 170B                                       0.0s
[+] Building 1.9s (3/3) FINISHED                                                
 => [internal] load build definition from redis-dockerfile                 0.2s
 => => transferring dockerfile: 323B                                       0.0s
 => [internal] load .dockerignore                                          0.3s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/redis:latest      1.6s
------
 > [internal] load metadata for docker.io/library/redis:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 5.7]: 403 Forbidden

### 期望的结果是什么？

部署成功

### 简单的复现代码/链接（可选）

```Java
ash-4.4# docker-compose build
[+] Building 0.0s (0/0)                                                         
[+] Building 0.4s (1/2)                                                         
 => [internal] load build definition from mysql-dockerfile                 0.3s 
 => => transferring dockerfile: 170B                                       0.0s
[+] Building 0.6s (2/3)                                                         
[+] Building 0.7s (2/3)                                                         
[+] Building 2.2s (3/3) FINISHED                                                
 => [internal] load build definition from mysql-dockerfile                 0.3s
 => => transferring dockerfile: 170B                                       0.0s
[+] Building 1.9s (3/3) FINISHED                                                
 => [internal] load build definition from redis-dockerfile                 0.2s
 => => transferring dockerfile: 323B                                       0.0s
 => [internal] load .dockerignore                                          0.3s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/redis:latest      1.6s
------
 > [internal] load metadata for docker.io/library/redis:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 5.7]: 403 Forbidden
```

**Comment by oddfar** [comment]
可以看下这边分享的教程：https://github.com/oddfar/campus-imaotai/discussions/categories/%E5%88%86%E4%BA%AB%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B

**Comment by nageshuizeii** [comment]
教程都看过了，没有使用docker-compose部署的

**Comment by oddfar** [comment]
`403 Forbidden` ：Docker Hub 访问受限
可以尝试手动拉取 redis 镜像，然后再运行 docker-compose build：

```bash
docker pull redis:latest
```

**Comment by nageshuizeii** [comment]
同样报错failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 5.7]: 403 Forbidden

已经拉取了redis

`ash-4.4# docker pull redis:latest
latest: Pulling from library/redis
efc2b5ad9eec: Already exists 
e1881a4a6fdd: Pull complete 
272d90b014a2: Pull complete 
1c6e055151a6: Pull complete 
6a4ea20e8d76: Pull complete 
1aa3206413a2: Pull complete 
4f4fb700ef54: Pull complete 
7f3c1f3a060e: Pull complete 
Digest: sha256:e59c42a34bdb950f988a1578504c31ce981096e3a18b83db1808bd7a32302e7f
Status: Downloaded newer image for redis:latest
docker.io/library/redis:latest
ash-4.4# docker-compose build
[+] Building 0.0s (0/0)                                                                                               
[+] Building 0.1s (0/2)                                                                                               
 => [internal] load build definition from redis-dockerfile                                                       0.1s
 => => transferring dockerfile: 323B                                                                             0.0s
 => [internal] load .dockerignore                                                                                0.0s
[+] Building 0.3s (2/3)                                                                                               
[+] Building 1.2s (5/8)                                                                                               
 => [internal] load build definition from redis-dockerfile                                                       0.2s
 => => transferring dockerfile: 323B                                                                             0.0s
[+] Building 1.4s (6/8)                                                                                               
 => [internal] load build definition from redis-dockerfile                                                       0.2s 
 => => transferring dockerfile: 323B                                                                             0.0s
 => [internal] load .dockerignore                                                                                0.2s
 => => transferring context: 2B                                                                                  0.0s
 => [internal] load metadata for docker.io/library/redis:latest                                                  0.0s
 => [1/4] FROM docker.io/library/redis                                                                           0.6s
 => [internal] load build context                                                                                0.2s
 => => transferring context: 96B                                                                                 0.0s
 => [2/4] RUN mkdir -p /home/campus/redis                                                                        0.5s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 5.7]: 403 Forbidden`

**Comment by oddfar** [comment]
那你试试 https://github.com/oddfar/campus-imaotai/discussions/374 sqlite版的

**Comment by nageshuizeii** [comment]
谢谢，的确可以用

**Comment by gemail1024** [comment]
> 谢谢，的确可以用

https://github.com/oddfar/campus-imaotai/discussions/374dokcker-compose

**Comment by gemail1024** [comment]
> 教程都看过了，没有使用docker-compose部署的

docker-compose可以参考这篇教程： https://www.bilibili.com/read/cv33190924

**Comment by nageshuizeii** [comment]
谢谢！用同一个作者的一键命令，已经启动了
