### ISSUE TITLE
请问怎么升级版本

### ISSUE THREAD

**Issue by ididaow** [oddfar/campus-imaotai#384]
1.0.12升级到1.0.13，直接解压把文件复制到docker文件夹里面就好了吗？需要修改docker-compose.yml文件吗？

**Comment by oddfar** [comment]
可以看下此文档：https://oddfar.github.io/campus-doc/pages/8f2aa8/#%E6%89%93%E5%8C%85%E6%9C%80%E6%96%B0%E6%96%87%E4%BB%B6
