### ISSUE TITLE
群晖里搭建服务启动不起来

### ISSUE THREAD

**Issue by wht11394** [oddfar/campus-imaotai#4]
![网页捕获_8-7-2023_172924_192 168 8 137](https://github.com/oddfar/campus-imaotai/assets/29323425/46e51e76-55f3-42ec-9484-ba2a9a479ce6)

**Comment by wht11394** [comment]
同时nginx容器的80端口报占用，改成别的可以启动了

**Comment by oddfar** [comment]
可能是jdk，换个就好，编辑“campus-dockerfile”文件改成`FROM 987846/jdk1.8
