### ISSUE TITLE
能出一个群辉的安装教程吗？

### ISSUE THREAD

**Issue by TangTree** [oddfar/campus-imaotai#40]
如题，群辉7之前的docker不支持docker-compose，安装7之后的版本，使用docker-compose，一直失败，🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by wspzf** [comment]
威联通部署也会失败，不知道能不能做成镜像发布到docker仓库?

**Comment by gamesang520** [comment]
群辉构建镜像的时候报错
