### ISSUE TITLE
104直升106，进入用户管理提示报错

### ISSUE THREAD

**Issue by tslace** [oddfar/campus-imaotai#48]
面板打开正常，唯独点开“用户管理”提示报错，并原先登录的账号无法显示。
`### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause' ### The error may exist in com/oddfar/campus/business/mapper/IUserMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT COUNT(*) AS total FROM i_user WHERE del_flag = 0 ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause' ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause'`

**Comment by oddfar** [comment]
V1.0.4及以下版本的，要重新部署

**Comment by tslace** [comment]
> V1.0.4及以下版本的，要重新部署

谢谢大佬，已重新部署并正常了。。
但是登录时填完验证码后，提示“登录错误，本地已记录日志”，这是什么原因呢？
而且没找到这个日志。。。

**Comment by oddfar** [comment]
> > V1.0.4及以下版本的，要重新部署
> 
> 谢谢大佬，已重新部署并正常了。。 但是登录时填完验证码后，提示“登录错误，本地已记录日志”，这是什么原因呢？ 而且没找到这个日志。
> 
> ps：我等第二天重新获取登录试试。。。

用 V1.0.6 修复版

**Comment by tslace** [comment]
已使用正常~~谢谢大佬~

**Comment by mzzgaopeng** [comment]
我也同样问题，用的1.0.6修复版

**Comment by oddfar** [comment]
> 我也同样问题，用的1.0.6修复版

可能是缓存，清下浏览器缓存
