### ISSUE TITLE
构建服务时报错

### ISSUE THREAD

**Issue by xiaobingnt** [oddfar/campus-imaotai#5]
执行docker-compose build时报错=> ERROR [campus-server internal] load metadata for docker.io/library/java:8
![73e8dcbde8efab343ca734ba4b00e2eb](https://github.com/oddfar/campus-imaotai/assets/52767861/1639ad01-e20e-4ed0-8cb6-90c0ed429c19)

**Comment by oddfar** [comment]
修改 `campus-dockerfile` 把FROM java:8换成FROM openjdk:8
然后删除镜像、容器重新试试
如果是amr架构换成FROM 987846/jdk1.8
