### ISSUE TITLE
这个文档写的是真的烂

### ISSUE THREAD

**Issue by xufeiwu123** [oddfar/campus-imaotai#51]

**Comment by Abeiheng** [comment]
那你觉得应该如何写文档

**Comment by oddfar** [comment]
如果您不知道如何有效、精准地表述，建议您先阅读《提问的智慧》
链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
***
你的提问：#50 tar -zxvf 压缩文件名.tar.gz 没找到
> 下载的压缩包，解压了没找到这个tar -zxvf`
***
首先，tar是Linux解压压缩包命令：[在linux中如何使用tar命令对文件打包压缩或解压 - 百度经验](http://www.baidu.com/link?url=_qZQAjkTVZ8YPRGGXf_eciq1oha_-2lcU45-xDHUPdTn6yzFYzrR6rjv---yG1t2BCoxLRInctNxPZ8BhyI2p6-clg8nke_ZNY7XW4rJkL_)

其次，非要挑刺？

> 在 [release](https://github.com/oddfar/campus-imaotai/releases) 页面下载压缩包并解压。
> 文件：campus-imt-xxxx.tar.gz
> 解压压缩包：tar -zxvf 压缩文件名.tar.gz

以上文档内容很明显的说明：下载文件，解压文件
还是你把`解压压缩包`理解成了里面的文件，非要写成`解压压缩包命令`这样的吗？
这文档写的不够让正常人读懂？非要截个图录个视频教教你怎么解压？还是你阅读理解有问题？

然后，本项目开源免费，我没收过你钱，你也没给过我好处。你咋不V我100让我一对一教你，而不是在这里找存在感

最后，傻逼东西

**Comment by tslace** [comment]
你这人也是搞笑。。还要多详细？直接给你台部署好的服务器算了。
这文档真看不懂的话还是手动玩吧。
