### ISSUE TITLE
登录界面报错系统接口404

### ISSUE THREAD

**Issue by morepeoplell** [oddfar/campus-imaotai#53]
您好，我下载您的tar.gz的压缩包解压，启动容器的时候发现campus-imt-v100_campus-server和 redis 启动就退出，这个很奇怪。
然后是我发现登录campus需要验证码，但是却没有验证码提示。并且报错系统接口404

**Comment by oddfar** [comment]
4个服务都要成功启动
> 第一次启动可能会失败，是因为 mysql 服务还没启动完成，campus-service 就启动了，等mysql启动完毕后，再启动一次即可 docker-compose up -d

**Comment by morepeoplell** [comment]
> 4个服务都要成功启动
> 
> > 第一次启动可能会失败，是因为 mysql 服务还没启动完成，campus-service 就启动了，等mysql启动完毕后，再启动一次即可 docker-compose up -d

四个服务只启动了俩个，另外俩个容器启动了就退出，没办法维持后台运行，加-d参数也不行。但是只启动了俩个容器也登录到容器管理界面了，只是登录不进去罢了

**Comment by morepeoplell** [comment]
web界面登录需要验证码，但是验证码刷不出来，这就很难受了
