### ISSUE TITLE
启动成功后几小时就又显示404接口错误

### ISSUE THREAD

**Issue by acp120** [oddfar/campus-imaotai#56]
启动好后 可能是后台某些程序没办法持续运行…… 不知道是啥原因

**Comment by acp120** [comment]
对了  我把80端口改了 发现 nginx时间长了就不启动了 我改回来试一下 晚点反馈

**Comment by acp120** [comment]
还是不行 好像是每天执行预约以后就自动掉 登录网页就是404

**Comment by oddfar** [comment]
可能内存不够，docker自动关闭了
