### ISSUE TITLE
成功运行后有几个不清楚的，请麻烦指点一下

### ISSUE THREAD

**Issue by xiaolietu** [oddfar/campus-imaotai#6]
1、admin登录的密码怎么修改，正常在用户处修改，需要旧密码。在用户管理中重置密码提示不允许操作超级管理员用户
2、i茅台→用户管理→用户管理，的到期时间无法编辑，不清楚这个时间会影响什么

**Comment by oddfar** [comment]
1、右上角个人中心->修改密码，默认原密码`admin123`
2、到期时间是token的到期时间，一次token管30天，到期了需要自己手动更改token，不能手动修改时间是bug，今天修复下

**Comment by bbingz** [comment]
手动更改 token 是什么意思，重新验证码是吧？

**Comment by bbingz** [comment]
还有系统用户里的致远用户可以删除吗？

**Comment by oddfar** [comment]
> 手动更改 token 是什么意思，重新验证码是吧？

对，重新添加账号，之前添加过就会更新token

**Comment by oddfar** [comment]
> 还有系统用户里的致远用户可以删除吗？

可以
