### ISSUE TITLE
这是个矛盾建议

### ISSUE THREAD

**Issue by Svip4807581** [oddfar/campus-imaotai#60]
首先，感谢作者做出来的预约系统，比较省事，其次，就是说个比较矛盾的事情，更新后，取消注册用户，我不理解，其次，取消注册用户后加那么多作者水印，这个我可以理解为防止别人贩卖，但是那个取消用户注册就无语了，如果朋友自己添加手机号，还得搭建的人自己给后台添加，不麻烦吗，都加了那么多水印，还能卖预约用户？建议恢复注册用户

**Comment by oddfar** [comment]
注册用户没取消过，新版本一直都有

**Comment by Svip4807581** [comment]
你好，麻烦问下从哪开启，这个每次手动添加太麻烦了

**Comment by oddfar** [comment]
默认开启的，`/register` 这个路径是注册页面

**Comment by Svip4807581** [comment]
好的谢谢，没问题了

**Comment by zyxjody** [comment]
你好，请问下我这个注册页面一直转圈是什么问题，显示在加载系统资源。login页面可以正常登录

**Comment by KUHE0000** [comment]
新注册用户，需要在后台手动配置权限，如何自动配置分配权限呢？
