### ISSUE TITLE
更新之后项目运行报错

### ISSUE THREAD

**Issue by Crazybbok** [oddfar/campus-imaotai#61]
通过文档里的教程，替换了html和jar目录及文件更新了1.0.6之后，访问后台查看用户管理的时候，出现以下错误，查了一下好像是数据库的查询问题，大佬帮忙看看

### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause' ### The error may exist in com/oddfar/campus/business/mapper/IUserMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT COUNT(*) AS total FROM i_user WHERE del_flag = 0 ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause' ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'del_flag' in 'where clause'

**Comment by oddfar** [comment]
低版本更新请重新部署

**Comment by Crazybbok** [comment]
好的，我是 1.0.4 更新上来的，那有办法导出数据库里用户信息吗？还是只能重新登录呢
