### ISSUE TITLE
1.0.6部署完一开始登录界面404，后来好了进去又报错

### ISSUE THREAD

**Issue by yxd-python** [oddfar/campus-imaotai#65]
<img width="1020" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/44567379/1f24c0b2-6af2-4014-8489-c5c2297d7c1d">

**Comment by yxd-python** [comment]
测试后发现，原因是我从1.04不能直接升级到1.06，需要先装1.05，再升级1.06

**Comment by oddfar** [comment]
直接重新装 `1.0.6` 就行，其他版本直接更新不行
