### ISSUE TITLE
JDK的AES加密异常java.security.InvalidKeyException: Illegal key size 的解决方法

### ISSUE THREAD

**Issue by ccqi3** [oddfar/campus-imaotai#69]
jdk1.8去`https://www.oracle.com/java/technologies/javase-jce8-downloads.html`下载jar包
将压缩包中的两个jar包放在 `%JDK_HOME%\jre\lib\security`目录下

**Comment by ccqi3** [comment]
jdk安装目录

**Comment by magaige** [comment]
Redis  这个里面的内容在哪里！你只说了导入数据库！
