### ISSUE TITLE
群晖直接启动不起来 docker

### ISSUE THREAD

**Issue by zry9815** [oddfar/campus-imaotai#7]
![image](https://github.com/oddfar/campus-imaotai/assets/67041916/813ef2ea-aa72-4b5a-90d6-975c8a9f9bb5)

**Comment by xuxiaohu6** [comment]
我的和你的一样，我直接把存储映射的那个给删了，就是不映射了。就可以进去了，但是后面我还是有点问题

**Comment by oddfar** [comment]
有点编程基础的话，试试直接部署，不用docker
环境准备：https://oddfar.github.io/campus-doc/pages/747f41/
快速启动：https://oddfar.github.io/campus-doc/pages/b784e7/
部署：https://oddfar.github.io/campus-doc/pages/3c5985/

**Comment by zadishu** [comment]
一样的问题，
