### ISSUE TITLE
arm64出错

### ISSUE THREAD

**Issue by shaufo** [oddfar/campus-imaotai#71]
=> [nginx internal] load build context                                                                                       0.1s
 => => transferring context: 12.41kB                                                                                          0.0s
 => CACHED [campus-imt-v106-campus-server 1/4] FROM docker.io/987846/jdk1.8@sha256:3bafd5449df765fc5002ec80267421aebd86c4ef1  0.0s
 => [campus-imt-v106-campus-server internal] load build context                                                               0.1s
 => => transferring context: 71B                                                                                              0.0s
 => ERROR [campus-imt-v106-campus-server 2/4] RUN mkdir -p /home/campus                                                       1.6s
------
 > [campus-imt-v106-campus-server 2/4] RUN mkdir -p /home/campus:
#0 1.416 exec /bin/sh: exec format error
------
failed to solve: executor failed running [/bin/sh -c mkdir -p /home/campus]: exit code: 1

**Comment by shaufo** [comment]
![微信截图_20230817014644](https://github.com/oddfar/campus-imaotai/assets/63514384/4e02085b-89ad-4ad8-bf97-33ea0ea6532e)

**Comment by wingswing1** [comment]
同，是不是不支持arm64？？

**Comment by gubaiqiu** [comment]
用 openjdk:8

**Comment by gubaiqiu** [comment]
此外，mysql5.7好像没有arm架构的，使用8版本的
