### ISSUE TITLE
领取耐力失败

### ISSUE THREAD

**Issue by Cy0ne** [oddfar/campus-imaotai#73]
申购后应和领取耐力中间有延迟，要不然有时会领取耐力失败

**Comment by Cy0ne** [comment]
![image](https://github.com/oddfar/campus-imaotai/assets/115539518/6a654405-30b0-41e8-b99d-2b56f822991b)
可明显看出 手动执行第二次的时候领取成功   猜想成功 （申购后应和领取耐力中间有延迟）才可领取耐力成功

**Comment by Cy0ne** [comment]
临时解决方法： 新增一个一样的任务 手机号可随机填写不影响（已测试） 希望大佬尽快修复吧 感谢

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/commit/3acd9065a8c27f1dd85d7b1be2a52b63c76bdc6a
feat：申购后延迟10秒领取耐力
已加，docker文件晚上发布
