### ISSUE TITLE
重新部署后无法启动server容器

### ISSUE THREAD

**Issue by cyxnzb** [oddfar/campus-imaotai#75]
报错如下：
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### SQL: SELECT  config_id,config_name,config_key,config_value,config_type,group_code,remark,create_time,create_user,update_time,update_user,del_flag  FROM sys_config   WHERE  del_flag=0

切换回原始版本也不行，但是之前部署就没啥问题

**Comment by oddfar** [comment]
数据库导入失败，手动把sql文件导入

**Comment by cyxnzb** [comment]
> 数据库导入失败，手动把sql文件导入

应该怎么导入，求教，主要docker环境下的不太会

**Comment by xuliyaheizi** [comment]
> > 数据库导入失败，手动把sql文件导入
> 
> 应该怎么导入，求教，主要docker环境下的不太会

 你用数据库工具，远程连接那个数据库，然后执行那个sql文件
![image](https://github.com/oddfar/campus-imaotai/assets/81568178/15ebd8ac-fb3d-4ca3-9412-d75cb23f423c)
