### ISSUE TITLE
Mac M2 docker 部署参考

### ISSUE THREAD

**Issue by dingysity** [oddfar/campus-imaotai#79]
# 操作步骤：

1. 下载release包
2. 修改docker-compost.yml文件：services.campus-mysql下增加platform: linux/x86_64
<img width="381" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/74894570/659fcbf9-29c0-4c9e-8aa2-5de6489f1949">

3. 修改campus-Dockerfile文件：将第二行改为：FROM eclipse-temurin:8
<img width="282" alt="image" src="https://github.com/oddfar/campus-imaotai/assets/74894570/3dbee51a-657c-4289-b298-3f720eb5f514">

4. docker-compose build 
5. docker-compose up -t

**Comment by tinoyoung** [comment]
能添加用户吗？我现在添加用户接口就报错： "获取验证码失败"

**Comment by weili80** [comment]
这方法有成功的么？
