### ISSUE TITLE
已经成功部署，但是没有找到用户名和密码。/login 页面登陆吗？大佬

### ISSUE THREAD

**Issue by maxime512** [oddfar/campus-imaotai#8]
![账号](https://github.com/oddfar/campus-imaotai/assets/62089958/baee5d61-edfa-4cba-b76f-d76614cfed1c)

**Comment by oddfar** [comment]
用户名 默认是 admin，密码admin123，这个页面登录后就有了

**Comment by maxime512** [comment]
谢谢大佬，抽时间回复。 感谢。 
 登录后台了，但是没有那个 申请日志的菜单栏。 是要自己去 app 看申购成狗了吗？ 还是可以调出来。

**Comment by oddfar** [comment]
有啊，系统管理->日志管理->操作日志
预约了才有日志记录，先手动点击预约，看看能不能有请求日志，没有则检查配置是否填写对
预约有两种：1、手动点击预约 2、每天9点05系统自动预约

**Comment by oddfar** [comment]
> 自动预留不用配置是吗

不用配置
