### ISSUE TITLE
群晖docker部署报错

### ISSUE THREAD

**Issue by zadishu** [oddfar/campus-imaotai#86]
root@DS220:/volume1/docker/campus-imt-V1.0.7# docker-compose up -d
[+] Running 2/4
 ⠿ Container campus-redis   Starting                                                                                                                                        62.6s
 ⠿ Container campus-mysql   Starting                                                                                                                                        62.6s
 ⠿ Container campus-server  Created                                                                                                                                          9.7s
 ⠿ Container campus-nginx   Created                                                                                                                                          7.4s
Error response from daemon: Bind mount failed: '/volume1/docker/campus-imt-V1.0.7/redis/data' does not exists
提示没有这个文件，这个文件去哪里找啊

**Comment by JUNEww** [comment]
同遇到这个问题

**Comment by zhao316678171** [comment]
那个文件缺少就新建那个，往后面继续试试，我部署完成但是卡在数据库没有权限，后来群辉搞了liunx虚拟机才跑起来

**Comment by oddfar** [comment]
https://github.com/oddfar/campus-imaotai/discussions/45#discussioncomment-6919752
