### ISSUE TITLE
=> ERROR [internal] load metadata for docker.io/library/java:8  

### ISSUE THREAD

**Issue by monobo1989** [oddfar/campus-imaotai#87]
请问这个要怎么办？

**Comment by Xh1275** [comment]
一样，这个报错

**Comment by monobo1989** [comment]
> 一样，这个报错

找到作者的回复了：
修改campus-dockerfile把FROM java:8换成FROM openjdk:8
然后删除镜像、容器重新试试
如果是amr架构换成FROM 987846/jdk1.8
