### ISSUE TITLE
旅行成功，不获取小茅运

### ISSUE THREAD

**Issue by yanqiangS** [oddfar/campus-imaotai#95]
![WechatIMG244](https://github.com/oddfar/campus-imaotai/assets/16951446/246f3bf7-c9b3-4c55-9a92-5260cb78899d)

观察好几天了，每天都会自动旅行，并且旅行成功
但是在i茅台中，小茅运并没有增加
为什么呢？

**Comment by Cy0ne** [comment]
这个地方有个bug  茅台app的问题，使用接口进行旅行后打开i茅台app可点击领取小茅运可领取！两次！

**Comment by acoooder** [comment]
同样的问题

**Comment by manBoooooooooooooom** [comment]
同样的问题

**Comment by android-1995** [comment]
貌似是只做了开始旅行的操作，没有领取旅行奖励的操作
@oddfar

**Comment by eric-wang95** [comment]
应该是客户端有刮刮乐操作，应用似乎没能解析
