### ISSUE TITLE
预约地址和实际地址距离过远

### ISSUE THREAD

**Issue by zadishu** [oddfar/campus-imaotai#98]
都预约到隔壁城市了

**Comment by oddfar** [comment]
类型有2个：
`预约本市出货量最大的门店`：从**本市**的门店列表里挑选出货量最大的门店
`预约最近的`：从**本省**门店列表里挑选

**Comment by zadishu** [comment]
门店飘的太远了，小县城都飘隔壁线程了

**Comment by jiacw214** [comment]
> 类型有2个： `预约本市出货量最大的门店`：从**本市**的门店列表里挑选出货量最大的门店 `预约最近的`：从**本省**门店列表里挑选

预约最近的这个类型能否改成从**所有**门店列表里挑选？或者单独出一个这样的类型？
我在河北省廊坊市的三河，申请兔茅本地的店有，但375ml*2的本地的店大部分时候没有，廊坊也偶尔没有，按说申请北京的就可以，也很近，但目前的规则会申请河北省更远的城市的门店，这与期望的不符。
像我这种在本地没有货在隔壁省有货而且地理位置更近的应该也不少
