### ISSUE TITLE
所有预约都报错

### ISSUE THREAD

**Issue by fengpan0403** [oddfar/campus-imaotai#99]
执行报错--[预约项目]：10213
[结果返回]：查询所在省市的投放产品和数量error，湖北省-10213

执行报错--[预约项目]：10056
[结果返回]：查询所在省市的投放产品和数量error，湖北省-10056

执行报错--[预约项目]：2478
[结果返回]：查询所在省市的投放产品和数量error，湖北省-2478

执行报错--[预约项目]：10214
[结果返回]：查询所在省市的投放产品和数量error，湖北省-10214

**Comment by toby1123yjh** [comment]
+1

**Comment by oneisall8955** [comment]
执行报错--[预约项目]：10213
[结果返回]：无效的申购信息，请关闭重试

执行报错--[预约项目]：10214
[结果返回]：无效的申购信息，请关闭重试
